FROM protoconf/protoconf-terraform:latest

# Add Maintainer Info
LABEL maintainer="Your Name <your.email@example.com>"

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy proto files
COPY ./src/terraform /app/src/terraform
