# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     # - go mod tidy
#     # you may remove this if you don't need go generate
#     # - go generate ./...
version: 2.0
builds:
  - id: protoconf-terraform
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/protoconf/protoconf-terraform/pkg/build.Version={{.Version}}
    goos:
      - linux
      # - windows
      - darwin
      # - freebsd
      # - openbsd
      # - solaris
    main: ./cmd/protoconf-terraform
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^fix(deps):"
brews:
  - # Name template of the recipe
    # Default to project name
    name: protoconf-terraform

    repository:
      owner: protoconf
      name: homebrew-tap

      token: "{{ .Env.DEPLOY_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    directory: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://www.protoconf.dev/"

    # Template of your app's description.
    # Default is empty.
    description: "Terraform integration for protoconf"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"
dockers:
  - id: protoconf-docker
    ids:
      - protoconf-terraform
    image_templates:
      - "protoconf/protoconf-terraform:latest"
      - "protoconf/protoconf-terraform:{{ .Tag }}"
      - "protoconf/protoconf-terraform:v{{ .Major }}"
      - "protoconf/protoconf-terraform:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/protoconf/protoconf-terraform:latest"
      - "ghcr.io/protoconf/protoconf-terraform:{{ .Tag }}"
      - "ghcr.io/protoconf/protoconf-terraform:{{ .Major }}"
      - "ghcr.io/protoconf/protoconf-terraform:{{ .Major }}.{{ .Minor }}"
    dockerfile: build/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/protoconf/protoconf-terraform"
      - "--platform=linux/amd64"
