syntax = "proto3";

// Provider: aws 6
package terraform.aws.datasources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsDatazoneDomain version is 0
message AwsDatazoneDomain {
  string arn = 1;

  string created_at = 2 [json_name = "created_at"];

  string description = 3;

  string domain_version = 4 [json_name = "domain_version"];

  string id = 5;

  string last_updated_at = 6 [json_name = "last_updated_at"];

  string managed_account_id = 7 [json_name = "managed_account_id"];

  string name = 8;

  string portal_url = 9 [json_name = "portal_url"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 10;

  string root_domain_unit_id = 11 [json_name = "root_domain_unit_id"];

  string status = 12;

  google.protobuf.Value for_each = 13 [json_name = "for_each"];

  repeated string depends_on = 14 [json_name = "depends_on"];

  int32 count = 15;

  string provider = 16;

  terraform.v1.Lifecycle lifecycle = 17;
}

// AwsDatazoneEnvironmentBlueprint version is 0
message AwsDatazoneEnvironmentBlueprint {
  string blueprint_provider = 1 [json_name = "blueprint_provider"];

  string description = 2;

  string domain_id = 3 [json_name = "domain_id"];

  string id = 4;

  bool managed = 5;

  string name = 6;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 7;

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;
}
