syntax = "proto3";

// Provider: aws 6
package terraform.aws.datasources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsInternetGateway version is 0
message AwsInternetGateway {
  string arn = 1;

  repeated Attachments attachments = 2;

  string id = 3;

  string internet_gateway_id = 4 [json_name = "internet_gateway_id"];

  string owner_id = 5 [json_name = "owner_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  map<string, string> tags = 7;

  repeated Filter filter = 8;

  repeated Timeouts timeouts = 9;

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;

  message Attachments {
    // state: string
    string state = 1;

    // vpc_id: string
    string vpc_id = 2 [json_name = "vpc_id"];
  }

  message Filter {
    string name = 1;

    repeated string values = 2;
  }

  message Timeouts {
    string read = 1;
  }
}
