syntax = "proto3";

// Provider: aws 6
package terraform.aws.datasources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsSecretsmanagerRandomPassword version is 0
message AwsSecretsmanagerRandomPassword {
  string exclude_characters = 1 [json_name = "exclude_characters"];

  bool exclude_lowercase = 2 [json_name = "exclude_lowercase"];

  bool exclude_numbers = 3 [json_name = "exclude_numbers"];

  bool exclude_punctuation = 4 [json_name = "exclude_punctuation"];

  bool exclude_uppercase = 5 [json_name = "exclude_uppercase"];

  string id = 6;

  bool include_space = 7 [json_name = "include_space"];

  int64 password_length = 8 [json_name = "password_length"];

  string random_password = 9 [json_name = "random_password"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 10;

  bool require_each_included_type = 11 [json_name = "require_each_included_type"];

  google.protobuf.Value for_each = 12 [json_name = "for_each"];

  repeated string depends_on = 13 [json_name = "depends_on"];

  int32 count = 14;

  string provider = 15;

  terraform.v1.Lifecycle lifecycle = 16;
}

// AwsSecretsmanagerSecret version is 0
message AwsSecretsmanagerSecret {
  string arn = 1;

  string created_date = 2 [json_name = "created_date"];

  string description = 3;

  string id = 4;

  string kms_key_id = 5 [json_name = "kms_key_id"];

  string last_changed_date = 6 [json_name = "last_changed_date"];

  string name = 7;

  string policy = 8;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 9;

  map<string, string> tags = 10;

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;
}

// AwsSecretsmanagerSecretRotation version is 0
message AwsSecretsmanagerSecretRotation {
  string id = 1;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 2;

  bool rotation_enabled = 3 [json_name = "rotation_enabled"];

  string rotation_lambda_arn = 4 [json_name = "rotation_lambda_arn"];

  repeated RotationRules rotation_rules = 5 [json_name = "rotation_rules"];

  string secret_id = 6 [json_name = "secret_id"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;

  message RotationRules {
    // automatically_after_days: number
    int64 automatically_after_days = 1 [json_name = "automatically_after_days"];

    // duration: string
    string duration = 2;

    // schedule_expression: string
    string schedule_expression = 3 [json_name = "schedule_expression"];
  }
}

// AwsSecretsmanagerSecretVersion version is 0
message AwsSecretsmanagerSecretVersion {
  string arn = 1;

  string created_date = 2 [json_name = "created_date"];

  string id = 3;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  string secret_binary = 5 [json_name = "secret_binary"];

  string secret_id = 6 [json_name = "secret_id"];

  string secret_string = 7 [json_name = "secret_string"];

  string version_id = 8 [json_name = "version_id"];

  string version_stage = 9 [json_name = "version_stage"];

  repeated string version_stages = 10 [json_name = "version_stages"];

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;
}

// AwsSecretsmanagerSecretVersions version is 0
message AwsSecretsmanagerSecretVersions {
  string arn = 1;

  bool include_deprecated = 2 [json_name = "include_deprecated"];

  string name = 3;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  string secret_id = 5 [json_name = "secret_id"];

  repeated Versions versions = 6;

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;

  message Versions {
    // created_time: string
    string created_time = 1 [json_name = "created_time"];

    // last_accessed_date: string
    string last_accessed_date = 2 [json_name = "last_accessed_date"];

    // version_id: string
    string version_id = 3 [json_name = "version_id"];

    // version_stages: list of string
    repeated string version_stages = 4 [json_name = "version_stages"];
  }
}

// AwsSecretsmanagerSecrets version is 0
message AwsSecretsmanagerSecrets {
  repeated string arns = 1;

  string id = 2;

  repeated string names = 3;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  repeated Filter filter = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;

  message Filter {
    string name = 1;

    repeated string values = 2;
  }
}
