syntax = "proto3";

// Provider: aws 6
package terraform.aws.datasources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsVpnConnection version is 0
message AwsVpnConnection {
  string category = 1;

  string core_network_arn = 2 [json_name = "core_network_arn"];

  string core_network_attachment_arn = 3 [json_name = "core_network_attachment_arn"];

  string customer_gateway_configuration = 4 [json_name = "customer_gateway_configuration"];

  string customer_gateway_id = 5 [json_name = "customer_gateway_id"];

  string gateway_association_state = 6 [json_name = "gateway_association_state"];

  string pre_shared_key_arn = 7 [json_name = "pre_shared_key_arn"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 8;

  repeated Routes routes = 9;

  string state = 10;

  map<string, string> tags = 11;

  string transit_gateway_id = 12 [json_name = "transit_gateway_id"];

  string type = 13;

  repeated VgwTelemetries vgw_telemetries = 14 [json_name = "vgw_telemetries"];

  string vpn_concentrator_id = 15 [json_name = "vpn_concentrator_id"];

  string vpn_connection_id = 16 [json_name = "vpn_connection_id"];

  string vpn_gateway_id = 17 [json_name = "vpn_gateway_id"];

  repeated Filter filter = 18;

  google.protobuf.Value for_each = 19 [json_name = "for_each"];

  repeated string depends_on = 20 [json_name = "depends_on"];

  int32 count = 21;

  string provider = 22;

  terraform.v1.Lifecycle lifecycle = 23;

  message Routes {
    // destination_cidr_block: string
    string destination_cidr_block = 1 [json_name = "destination_cidr_block"];

    // source: string
    string source = 2;

    // state: string
    string state = 3;
  }

  message VgwTelemetries {
    // accepted_route_count: number
    int64 accepted_route_count = 1 [json_name = "accepted_route_count"];

    // last_status_change: string
    string last_status_change = 2 [json_name = "last_status_change"];

    // outside_ip_address: string
    string outside_ip_address = 3 [json_name = "outside_ip_address"];

    // status: string
    string status = 4;

    // status_message: string
    string status_message = 5 [json_name = "status_message"];
  }

  message Filter {
    string name = 1;

    repeated string values = 2;
  }
}

// AwsVpnGateway version is 0
message AwsVpnGateway {
  string amazon_side_asn = 1 [json_name = "amazon_side_asn"];

  string arn = 2;

  string attached_vpc_id = 3 [json_name = "attached_vpc_id"];

  string availability_zone = 4 [json_name = "availability_zone"];

  string id = 5;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  string state = 7;

  map<string, string> tags = 8;

  repeated Filter filter = 9;

  repeated Timeouts timeouts = 10;

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message Filter {
    string name = 1;

    repeated string values = 2;
  }

  message Timeouts {
    string read = 1;
  }
}
