syntax = "proto3";

// Provider: aws 6
package terraform.aws.datasources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsWorkspacesBundle version is 0
message AwsWorkspacesBundle {
  string bundle_id = 1 [json_name = "bundle_id"];

  repeated ComputeType compute_type = 2 [json_name = "compute_type"];

  string description = 3;

  string id = 4;

  string name = 5;

  string owner = 6;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 7;

  repeated RootStorage root_storage = 8 [json_name = "root_storage"];

  repeated UserStorage user_storage = 9 [json_name = "user_storage"];

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;

  message ComputeType {
    // name: string
    string name = 1;
  }

  message RootStorage {
    // capacity: string
    string capacity = 1;
  }

  message UserStorage {
    // capacity: string
    string capacity = 1;
  }
}

// AwsWorkspacesDirectory version is 0
message AwsWorkspacesDirectory {
  repeated ActiveDirectoryConfig active_directory_config = 1 [json_name = "active_directory_config"];

  string alias = 2;

  repeated CertificateBasedAuthProperties certificate_based_auth_properties = 3 [json_name = "certificate_based_auth_properties"];

  string customer_user_name = 4 [json_name = "customer_user_name"];

  string directory_id = 5 [json_name = "directory_id"];

  string directory_name = 6 [json_name = "directory_name"];

  string directory_type = 7 [json_name = "directory_type"];

  repeated string dns_ip_addresses = 8 [json_name = "dns_ip_addresses"];

  string iam_role_id = 9 [json_name = "iam_role_id"];

  string id = 10;

  repeated string ip_group_ids = 11 [json_name = "ip_group_ids"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 12;

  string registration_code = 13 [json_name = "registration_code"];

  repeated SamlProperties saml_properties = 14 [json_name = "saml_properties"];

  repeated SelfServicePermissions self_service_permissions = 15 [json_name = "self_service_permissions"];

  repeated string subnet_ids = 16 [json_name = "subnet_ids"];

  map<string, string> tags = 17;

  string tenancy = 18;

  string user_identity_type = 19 [json_name = "user_identity_type"];

  repeated WorkspaceAccessProperties workspace_access_properties = 20 [json_name = "workspace_access_properties"];

  repeated WorkspaceCreationProperties workspace_creation_properties = 21 [json_name = "workspace_creation_properties"];

  string workspace_directory_description = 22 [json_name = "workspace_directory_description"];

  string workspace_directory_name = 23 [json_name = "workspace_directory_name"];

  string workspace_security_group_id = 24 [json_name = "workspace_security_group_id"];

  string workspace_type = 25 [json_name = "workspace_type"];

  google.protobuf.Value for_each = 26 [json_name = "for_each"];

  repeated string depends_on = 27 [json_name = "depends_on"];

  int32 count = 28;

  string provider = 29;

  terraform.v1.Lifecycle lifecycle = 30;

  message ActiveDirectoryConfig {
    // domain_name: string
    string domain_name = 1 [json_name = "domain_name"];

    // service_account_secret_arn: string
    string service_account_secret_arn = 2 [json_name = "service_account_secret_arn"];
  }

  message CertificateBasedAuthProperties {
    // certificate_authority_arn: string
    string certificate_authority_arn = 1 [json_name = "certificate_authority_arn"];

    // status: string
    string status = 2;
  }

  message SamlProperties {
    // relay_state_parameter_name: string
    string relay_state_parameter_name = 1 [json_name = "relay_state_parameter_name"];

    // status: string
    string status = 2;

    // user_access_url: string
    string user_access_url = 3 [json_name = "user_access_url"];
  }

  message SelfServicePermissions {
    // change_compute_type: bool
    bool change_compute_type = 1 [json_name = "change_compute_type"];

    // increase_volume_size: bool
    bool increase_volume_size = 2 [json_name = "increase_volume_size"];

    // rebuild_workspace: bool
    bool rebuild_workspace = 3 [json_name = "rebuild_workspace"];

    // restart_workspace: bool
    bool restart_workspace = 4 [json_name = "restart_workspace"];

    // switch_running_mode: bool
    bool switch_running_mode = 5 [json_name = "switch_running_mode"];
  }

  message WorkspaceAccessProperties {
    // device_type_android: string
    string device_type_android = 1 [json_name = "device_type_android"];

    // device_type_chromeos: string
    string device_type_chromeos = 2 [json_name = "device_type_chromeos"];

    // device_type_ios: string
    string device_type_ios = 3 [json_name = "device_type_ios"];

    // device_type_linux: string
    string device_type_linux = 4 [json_name = "device_type_linux"];

    // device_type_osx: string
    string device_type_osx = 5 [json_name = "device_type_osx"];

    // device_type_web: string
    string device_type_web = 6 [json_name = "device_type_web"];

    // device_type_windows: string
    string device_type_windows = 7 [json_name = "device_type_windows"];

    // device_type_zeroclient: string
    string device_type_zeroclient = 8 [json_name = "device_type_zeroclient"];
  }

  message WorkspaceCreationProperties {
    // custom_security_group_id: string
    string custom_security_group_id = 1 [json_name = "custom_security_group_id"];

    // default_ou: string
    string default_ou = 2 [json_name = "default_ou"];

    // enable_internet_access: bool
    bool enable_internet_access = 3 [json_name = "enable_internet_access"];

    // enable_maintenance_mode: bool
    bool enable_maintenance_mode = 4 [json_name = "enable_maintenance_mode"];

    // user_enabled_as_local_administrator: bool
    bool user_enabled_as_local_administrator = 5 [json_name = "user_enabled_as_local_administrator"];
  }
}

// AwsWorkspacesImage version is 0
message AwsWorkspacesImage {
  string description = 1;

  string id = 2;

  string image_id = 3 [json_name = "image_id"];

  string name = 4;

  string operating_system_type = 5 [json_name = "operating_system_type"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  string required_tenancy = 7 [json_name = "required_tenancy"];

  string state = 8;

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// AwsWorkspacesWorkspace version is 0
message AwsWorkspacesWorkspace {
  string bundle_id = 1 [json_name = "bundle_id"];

  string computer_name = 2 [json_name = "computer_name"];

  string directory_id = 3 [json_name = "directory_id"];

  string id = 4;

  string ip_address = 5 [json_name = "ip_address"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  bool root_volume_encryption_enabled = 7 [json_name = "root_volume_encryption_enabled"];

  string state = 8;

  map<string, string> tags = 9;

  string user_name = 10 [json_name = "user_name"];

  bool user_volume_encryption_enabled = 11 [json_name = "user_volume_encryption_enabled"];

  string volume_encryption_key = 12 [json_name = "volume_encryption_key"];

  string workspace_id = 13 [json_name = "workspace_id"];

  repeated WorkspaceProperties workspace_properties = 14 [json_name = "workspace_properties"];

  google.protobuf.Value for_each = 15 [json_name = "for_each"];

  repeated string depends_on = 16 [json_name = "depends_on"];

  int32 count = 17;

  string provider = 18;

  terraform.v1.Lifecycle lifecycle = 19;

  message WorkspaceProperties {
    // compute_type_name: string
    string compute_type_name = 1 [json_name = "compute_type_name"];

    // root_volume_size_gib: number
    int64 root_volume_size_gib = 2 [json_name = "root_volume_size_gib"];

    // running_mode: string
    string running_mode = 3 [json_name = "running_mode"];

    // running_mode_auto_stop_timeout_in_minutes: number
    int64 running_mode_auto_stop_timeout_in_minutes = 4 [
      json_name = "running_mode_auto_stop_timeout_in_minutes"
    ];

    // user_volume_size_gib: number
    int64 user_volume_size_gib = 5 [json_name = "user_volume_size_gib"];
  }
}
