syntax = "proto2";

// Provider: null 3
package terraform.null.provider.v3;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// Null version is 0
message Null {
  optional google.protobuf.Value for_each = 1 [json_name = "for_each"];

  repeated string depends_on = 2 [json_name = "depends_on"];

  optional int32 count = 3;

  optional string provider = 4;

  optional terraform.v1.Lifecycle lifecycle = 5;

  optional string alias = 6;

  optional string provider_fqdn = 7 [default = "registry.terraform.io/hashicorp/null"];

  optional string provider_version = 8 [default = "3.2.4"];
}
