syntax = "proto3";

package terraform.v1;

import "google/protobuf/struct.proto";

message Terraform {
  Resources resource = 1;

  Datasources data = 2;

  Providers provider = 3;

  map<string, Variable> variable = 4;

  map<string, Output> output = 5;

  map<string, string> locals = 6;

  map<string, google.protobuf.Struct> module = 7;

  TerraformSettings terraform = 8;

  message Resources {
  }

  message Datasources {
  }

  message Providers {
  }

  message Variable {
    string type = 1;

    string description = 2;

    string default = 3;
  }

  message Output {
    string value = 1;
  }

  message TerraformSettings {
    string required_version = 1 [json_name = "required_version"];

    map<string, Provider> required_providers = 2 [json_name = "required_providers"];

    Backend backend = 3;

    message Provider {
      string source = 1;

      string version = 2;
    }

    message Backend {
      oneof config {
        BackendLocal local = 1;

        BackendRemote remote = 2;

        BackendS3 s3 = 3;

        BackendConsul consul = 4;

        BackendAzurerm azurerm = 5;

        BackendGCS gcs = 6;

        BackendHTTP http = 7;

        BackendKubernetes kubernetes = 8;

        BackendPg pg = 9;
      }

      message BackendLocal {
        string path = 1;

        string workspace_dir = 2 [json_name = "workspace_dir"];
      }

      message BackendRemote {
        // (Optional) The remote backend hostname to connect to. Defaults to app.terraform.io.
        string hostname = 1;

        // (Required) The name of the organization containing the targeted workspace(s).
        string organization = 2;

        // (Optional) The token used to authenticate with the remote backend. We recommend omitting the token from the configuration, and instead using `terraform login` or manually configuring `credentials` in the CLI config file.
        string token = 3;

        // (Required) A block specifying which remote workspace(s) to use. The workspaces block supports the following keys
        Workspace workspaces = 4;

        message Workspace {
          // (Optional) The full name of one remote workspace. When configured, only the default workspace can be used. This option conflicts with prefix.
          string name = 1;

          // (Optional) A prefix used in the names of one or more remote workspaces, all of which can be used with this configuration. The full workspace names are used in Terraform Cloud, and the short names (minus the prefix) are used on the command line for Terraform CLI workspaces. If omitted, only the default workspace can be used. This option conflicts with name.
          string prefix = 2;
        }
      }

      message BackendS3 {
        string region = 1;

        string access_key = 2 [json_name = "access_key"];

        string secret_key = 3 [json_name = "secret_key"];

        string iam_endpoint = 4 [json_name = "iam_endpoint"];

        string max_retries = 5 [json_name = "max_retries"];

        string profile = 6;

        string shared_credentials_file = 7 [json_name = "shared_credentials_file"];

        string skip_credentials_validation = 8 [json_name = "skip_credentials_validation"];

        string skip_region_validation = 9 [json_name = "skip_region_validation"];

        string skip_metadata_api_check = 10 [json_name = "skip_metadata_api_check"];

        string sts_endpoint = 11 [json_name = "sts_endpoint"];

        string token = 12;

        string assume_role_duration_seconds = 13 [json_name = "assume_role_duration_seconds"];

        string assume_role_policy = 14 [json_name = "assume_role_policy"];

        string assume_role_policy_arns = 15 [json_name = "assume_role_policy_arns"];

        string assume_role_tags = 16 [json_name = "assume_role_tags"];

        string assume_role_transitive_tag_keys = 17 [json_name = "assume_role_transitive_tag_keys"];

        string external_id = 18 [json_name = "external_id"];

        string role_arn = 19 [json_name = "role_arn"];

        string session_name = 20 [json_name = "session_name"];

        string bucket = 21;

        string key = 22;

        string acl = 23;

        string encrypt = 24;

        string endpoint = 25;

        string force_path_style = 26 [json_name = "force_path_style"];

        string kms_key_id = 27 [json_name = "kms_key_id"];

        string sse_customer_key = 28 [json_name = "sse_customer_key"];

        string workspace_key_prefix = 29 [json_name = "workspace_key_prefix"];

        string dynamodb_endpoint = 30 [json_name = "dynamodb_endpoint"];

        string dynamodb_table = 31 [json_name = "dynamodb_table"];
      }

      message BackendConsul {
        // (Required) Path in the Consul KV store.
        string path = 1 [json_name = "path"];

        // (Optional) Consul Access Token.
        string access_token = 2 [json_name = "access_token"];

        // (Optional) DNS name and port of your Consul endpoint specified in the format dnsname:port.
        string address = 3 [json_name = "address"];

        // (Optional) Specifies what protocol to use when talking to the given address — either http or https. SSL support can also be triggered by setting the environment variable CONSUL_HTTP_SSL to true.
        string scheme = 4 [json_name = "scheme"];

        // (Optional) The datacenter to use. Defaults to that of the agent.
        string datacenter = 5 [json_name = "datacenter"];

        // (Optional) HTTP Basic Authentication credentials to be used when communicating with Consul, in the format of either user or user:pass.
        string http_auth = 6 [json_name = "http_auth"];

        // (Optional) true to compress the state data using gzip, or false (the default) to leave it uncompressed.
        string gzip = 7 [json_name = "gzip"];

        // (Optional) false to disable locking. Defaults to true.
        string lock = 8 [json_name = "lock"];

        // (Optional) A path to a PEM-encoded certificate authority used to verify the remote agent's certificate.
        string ca_file = 9 [json_name = "ca_file"];

        // (Optional) A path to a PEM-encoded certificate provided to the remote agent; requires use of key_file.
        string cert_file = 10 [json_name = "cert_file"];

        // (Optional) A path to a PEM-encoded private key, required if cert_file is specified.
        string key_file = 11 [json_name = "key_file"];
      }

      message BackendAzurerm {
        // (Required) The Name of the Storage Account.
        string storage_account_name = 1 [json_name = "storage_account_name"];

        // (Required) The Name of the Storage Container within the Storage Account.
        string container_name = 2 [json_name = "container_name"];

        // (Required) The name of the Blob used to retrieve/store Terraform's State file inside the Storage Container.
        string key = 3 [json_name = "key"];

        // (Optional) The Azure Environment which should be used. Possible values are public, china, german, stack and usgovernment. Defaults to public.
        string environment = 4 [json_name = "environment"];

        // (Optional) The Custom Endpoint for Azure Resource Manager.
        string endpoint = 5 [json_name = "endpoint"];

        // (Optional) The Hostname of the Azure Metadata Service.
        string metadata_host = 6 [json_name = "metadata_host"];

        // (Optional) Should the Blob used to store the Terraform Statefile be snapshotted before use? Defaults to false.
        string snapshot = 7 [json_name = "snapshot"];

        // (Required for AzureAD/MSI auth) The Name of the Resource Group in which the Storage Account exists.
        string resource_group_name = 8 [json_name = "resource_group_name"];

        // (Optional) The path to a custom Managed Service Identity endpoint.
        string msi_endpoint = 9 [json_name = "msi_endpoint"];

        // (Optional) The Subscription ID in which the Storage Account exists.
        string subscription_id = 10 [json_name = "subscription_id"];

        // (Optional) The Tenant ID in which the Subscription exists.
        string tenant_id = 11 [json_name = "tenant_id"];

        // (Optional) The Client ID of the Service Principal.
        string client_id = 12 [json_name = "client_id"];

        // (Optional) The Client Secret of the Service Principal.
        string client_secret = 13 [json_name = "client_secret"];

        // (Optional) The password associated with the Client Certificate specified in client_certificate_path.
        string client_certificate_password = 14 [json_name = "client_certificate_password"];

        // (Optional) The path to the PFX file used as the Client Certificate when authenticating as a Service Principal.
        string client_certificate_path = 15 [json_name = "client_certificate_path"];

        // (Optional) The SAS Token used to access the Blob Storage Account.
        string sas_token = 16 [json_name = "sas_token"];

        // (Optional) The Access Key used to access the Blob Storage Account.
        string access_key = 17 [json_name = "access_key"];

        // (Optional) Should Managed Service Identity authentication be used?
        string use_msi = 18 [json_name = "use_msi"];

        // (Optional) Should Terraform use AzureAD authentication to access the Blob?
        string use_azuread_auth = 19 [json_name = "use_azuread_auth"];

        // (Optional) Should OIDC authentication be used?
        string use_oidc = 20 [json_name = "use_oidc"];

        // (Optional) The bearer token for the request to the OIDC provider.
        string oidc_request_token = 21 [json_name = "oidc_request_token"];

        // (Optional) The URL for the OIDC provider from which to request an ID token.
        string oidc_request_url = 22 [json_name = "oidc_request_url"];

        // (Optional) The OIDC ID token for use when authenticating using OIDC.
        string oidc_token = 23 [json_name = "oidc_token"];

        // (Optional) The path to a file containing an OIDC ID token for use when authenticating using OIDC.
        string oidc_token_file_path = 24 [json_name = "oidc_token_file_path"];
      }

      message BackendGCS {
        // (Required) The name of the GCS bucket. This bucket must exist before Terraform can be configured to use it.
        string bucket = 1 [json_name = "bucket"];

        // (Optional) Local path to Google Cloud Platform account credentials in JSON format. If unset, the path to your default credentials will be used (set via gcloud auth application-default login or GOOGLE_APPLICATION_CREDENTIALS).
        string credentials = 2 [json_name = "credentials"];

        // (Optional) The service account to impersonate for accessing the State Bucket.
        string impersonate_service_account = 3 [json_name = "impersonate_service_account"];

        // (Optional) The delegation chain for impersonating a service account.
        string impersonate_service_account_delegates = 4 [json_name = "impersonate_service_account_delegates"];

        // (Optional) A temporary OAuth 2.0 access token obtained from the Google Authorization server.
        string access_token = 5 [json_name = "access_token"];

        // (Optional) GCS prefix inside the bucket. Named states for workspaces are stored in an object called <prefix>/<name>.tfstate.
        string prefix = 6 [json_name = "prefix"];

        // (Optional) A 32 byte base64 encoded customer supplied encryption key (CSEK) used to encrypt all state.
        string encryption_key = 7 [json_name = "encryption_key"];

        // (Optional) A Cloud KMS key (KMS_KEY) name used for encryption — projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{name}.
        string kms_encryption_key = 8 [json_name = "kms_encryption_key"];

        // (Optional) A URL containing the protocol, the DNS name pointing to a Private Service Connect endpoint, and the path for the Cloud Storage API (typically /storage/v1/b).
        string storage_custom_endpoint = 9 [json_name = "storage_custom_endpoint"];
      }

      message BackendHTTP {
        // (Required) The address of the REST endpoint.
        string address = 1 [json_name = "address"];

        // (Optional) HTTP method to use when updating state. Defaults to POST.
        string update_method = 2 [json_name = "update_method"];

        // (Optional) The address of the lock REST endpoint. Defaults to disabled.
        string lock_address = 3 [json_name = "lock_address"];

        // (Optional) The HTTP method to use when locking. Defaults to LOCK.
        string lock_method = 4 [json_name = "lock_method"];

        // (Optional) The address of the unlock REST endpoint. Defaults to disabled.
        string unlock_address = 5 [json_name = "unlock_address"];

        // (Optional) The HTTP method to use when unlocking. Defaults to UNLOCK.
        string unlock_method = 6 [json_name = "unlock_method"];

        // (Optional) The username for HTTP basic authentication.
        string username = 7 [json_name = "username"];

        // (Optional) The password for HTTP basic authentication.
        string password = 8 [json_name = "password"];

        // (Optional) Whether to skip TLS verification. Defaults to false.
        string skip_cert_verification = 9 [json_name = "skip_cert_verification"];

        // (Optional) The number of HTTP request retries. Defaults to 2.
        string retry_max = 10 [json_name = "retry_max"];

        // (Optional) The minimum time in seconds to wait between HTTP request attempts. Defaults to 1.
        string retry_wait_min = 11 [json_name = "retry_wait_min"];

        // (Optional) The maximum time in seconds to wait between HTTP request attempts. Defaults to 30.
        string retry_wait_max = 12 [json_name = "retry_wait_max"];

        // (Optional) A PEM-encoded CA certificate chain used by the client to verify server certificates during TLS authentication.
        string client_ca_certificate_pem = 13 [json_name = "client_ca_certificate_pem"];

        // (Optional) A PEM-encoded certificate used by the server to verify the client during mutual TLS (mTLS) authentication.
        string client_certificate_pem = 14 [json_name = "client_certificate_pem"];

        // (Optional) A PEM-encoded private key, required if client_certificate_pem is specified.
        string client_private_key_pem = 15 [json_name = "client_private_key_pem"];
      }

      message BackendKubernetes {
        // (Required) Suffix used when creating the secret. The secret will be named in the format: tfstate-{workspace}-{secret_suffix}.
        string secret_suffix = 1 [json_name = "secret_suffix"];

        // (Optional) Map of additional labels to be applied to the secret and config map.
        string labels = 2 [json_name = "labels"];

        // (Optional) Namespace to store the secret in.
        string namespace = 3 [json_name = "namespace"];

        // (Optional) Used to authenticate to the cluster from inside a pod.
        string in_cluster_config = 4 [json_name = "in_cluster_config"];

        // (Optional) Load local kubeconfig.
        string load_config_file = 5 [json_name = "load_config_file"];

        // (Optional) The hostname (in form of URI) of the Kubernetes API.
        string host = 6 [json_name = "host"];

        // (Optional) The username to use for HTTP basic authentication when accessing the Kubernetes API.
        string username = 7 [json_name = "username"];

        // (Optional) The password to use for HTTP basic authentication when accessing the Kubernetes API.
        string password = 8 [json_name = "password"];

        // (Optional) Whether server should be accessed without verifying the TLS certificate.
        string insecure = 9 [json_name = "insecure"];

        // (Optional) PEM-encoded client certificate for TLS authentication.
        string client_certificate = 10 [json_name = "client_certificate"];

        // (Optional) PEM-encoded client certificate key for TLS authentication.
        string client_key = 11 [json_name = "client_key"];

        // (Optional) PEM-encoded root certificates bundle for TLS authentication.
        string cluster_ca_certificate = 12 [json_name = "cluster_ca_certificate"];

        // (Optional) A list of paths to kubeconfig files.
        string config_paths = 13 [json_name = "config_paths"];

        // (Optional) Path to the kubeconfig file. Can be sourced from KUBE_CONFIG_PATH.
        string config_path = 14 [json_name = "config_path"];

        // (Optional) Context to choose from the config file. Can be sourced from KUBE_CTX.
        string config_context = 15 [json_name = "config_context"];

        // (Optional) Authentication info context of the kube config (--user flag in kubectl).
        string config_context_auth_info = 16 [json_name = "config_context_auth_info"];

        // (Optional) Cluster context of the kube config (--cluster flag in kubectl).
        string config_context_cluster = 17 [json_name = "config_context_cluster"];

        // (Optional) Token of your service account.
        string token = 18 [json_name = "token"];

        // (Optional) Configuration block to use an exec-based credential plugin.
        string exec = 19 [json_name = "exec"];
      }

      message BackendPg {
        // (Required) Postgres connection string; a postgres:// URL.
        string conn_str = 1 [json_name = "conn_str"];

        // (Optional) Name of the automatically-managed Postgres schema to store state. Defaults to terraform_remote_state.
        string schema_name = 2 [json_name = "schema_name"];

        // (Optional) If set to true, the Postgres schema must already exist. Defaults to false.
        string skip_schema_creation = 3 [json_name = "skip_schema_creation"];

        // (Optional) If set to true, the Postgres table must already exist.
        string skip_table_creation = 4 [json_name = "skip_table_creation"];

        // (Optional) If set to true, the Postgres index must already exist.
        string skip_index_creation = 5 [json_name = "skip_index_creation"];
      }
    }
  }
}
