// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: proto/protoconf-terraform/config/v1/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerraformPluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentAddress string `protobuf:"bytes,1,opt,name=agent_address,json=agent-address,proto3" json:"agent_address,omitempty"`
	ConfigPath   string `protobuf:"bytes,2,opt,name=config_path,json=config-path,proto3" json:"config_path,omitempty"`
}

func (x *TerraformPluginConfig) Reset() {
	*x = TerraformPluginConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerraformPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerraformPluginConfig) ProtoMessage() {}

func (x *TerraformPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerraformPluginConfig.ProtoReflect.Descriptor instead.
func (*TerraformPluginConfig) Descriptor() ([]byte, []int) {
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *TerraformPluginConfig) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *TerraformPluginConfig) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type SubscriptionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SubscriptionConfig) Reset() {
	*x = SubscriptionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionConfig) ProtoMessage() {}

func (x *SubscriptionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionConfig.ProtoReflect.Descriptor instead.
func (*SubscriptionConfig) Descriptor() ([]byte, []int) {
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionConfig) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_proto_protoconf_terraform_config_v1_config_proto protoreflect.FileDescriptor

var file_proto_protoconf_terraform_config_v1_config_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e,
	0x66, 0x2d, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x22, 0x5f, 0x0a,
	0x15, 0x54, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2d, 0x70, 0x61, 0x74, 0x68, 0x22, 0x28,
	0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x2d, 0x74, 0x65, 0x72, 0x72, 0x61,
	0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6e, 0x66, 0x2d, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_protoconf_terraform_config_v1_config_proto_rawDescOnce sync.Once
	file_proto_protoconf_terraform_config_v1_config_proto_rawDescData = file_proto_protoconf_terraform_config_v1_config_proto_rawDesc
)

func file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP() []byte {
	file_proto_protoconf_terraform_config_v1_config_proto_rawDescOnce.Do(func() {
		file_proto_protoconf_terraform_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_protoconf_terraform_config_v1_config_proto_rawDescData)
	})
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescData
}

var file_proto_protoconf_terraform_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_protoconf_terraform_config_v1_config_proto_goTypes = []interface{}{
	(*TerraformPluginConfig)(nil), // 0: config.v1.TerraformPluginConfig
	(*SubscriptionConfig)(nil),    // 1: config.v1.SubscriptionConfig
}
var file_proto_protoconf_terraform_config_v1_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_protoconf_terraform_config_v1_config_proto_init() }
func file_proto_protoconf_terraform_config_v1_config_proto_init() {
	if File_proto_protoconf_terraform_config_v1_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerraformPluginConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_protoconf_terraform_config_v1_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_protoconf_terraform_config_v1_config_proto_goTypes,
		DependencyIndexes: file_proto_protoconf_terraform_config_v1_config_proto_depIdxs,
		MessageInfos:      file_proto_protoconf_terraform_config_v1_config_proto_msgTypes,
	}.Build()
	File_proto_protoconf_terraform_config_v1_config_proto = out.File
	file_proto_protoconf_terraform_config_v1_config_proto_rawDesc = nil
	file_proto_protoconf_terraform_config_v1_config_proto_goTypes = nil
	file_proto_protoconf_terraform_config_v1_config_proto_depIdxs = nil
}
