// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: proto/protoconf_terraform/config/v1/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerraformPluginConfig_LogLevel int32

const (
	// NoLevel is a special level used to indicate that no level has been
	// set and allow for a default to be used.
	TerraformPluginConfig_LOG_LEVEL_UNSPECIFIED TerraformPluginConfig_LogLevel = 0
	// Trace is the most verbose level. Intended to be used for the tracing
	// of actions in code, such as function enters/exits, etc.
	TerraformPluginConfig_LOG_LEVEL_TRACE TerraformPluginConfig_LogLevel = 1
	// Debug information for programmer low-level analysis.
	TerraformPluginConfig_LOG_LEVEL_DEBUG TerraformPluginConfig_LogLevel = 2
	// Info information about steady state operations.
	TerraformPluginConfig_LOG_LEVEL_INFO TerraformPluginConfig_LogLevel = 3
	// Warn information about rare but handled events.
	TerraformPluginConfig_LOG_LEVEL_WARN TerraformPluginConfig_LogLevel = 4
	// Error information about unrecoverable events.
	TerraformPluginConfig_LOG_LEVEL_ERROR TerraformPluginConfig_LogLevel = 5
	// Off disables all logging output.
	TerraformPluginConfig_LOG_LEVEL_OFF TerraformPluginConfig_LogLevel = 6
)

// Enum value maps for TerraformPluginConfig_LogLevel.
var (
	TerraformPluginConfig_LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_TRACE",
		2: "LOG_LEVEL_DEBUG",
		3: "LOG_LEVEL_INFO",
		4: "LOG_LEVEL_WARN",
		5: "LOG_LEVEL_ERROR",
		6: "LOG_LEVEL_OFF",
	}
	TerraformPluginConfig_LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_TRACE":       1,
		"LOG_LEVEL_DEBUG":       2,
		"LOG_LEVEL_INFO":        3,
		"LOG_LEVEL_WARN":        4,
		"LOG_LEVEL_ERROR":       5,
		"LOG_LEVEL_OFF":         6,
	}
)

func (x TerraformPluginConfig_LogLevel) Enum() *TerraformPluginConfig_LogLevel {
	p := new(TerraformPluginConfig_LogLevel)
	*p = x
	return p
}

func (x TerraformPluginConfig_LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerraformPluginConfig_LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_protoconf_terraform_config_v1_config_proto_enumTypes[0].Descriptor()
}

func (TerraformPluginConfig_LogLevel) Type() protoreflect.EnumType {
	return &file_proto_protoconf_terraform_config_v1_config_proto_enumTypes[0]
}

func (x TerraformPluginConfig_LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerraformPluginConfig_LogLevel.Descriptor instead.
func (TerraformPluginConfig_LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP(), []int{0, 0}
}

type TerraformPluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentAddress  string                         `protobuf:"bytes,1,opt,name=agent_address,json=agent-address,proto3" json:"agent_address,omitempty"`
	ConfigPath    string                         `protobuf:"bytes,2,opt,name=config_path,json=config-path,proto3" json:"config_path,omitempty"`
	TerraformRoot string                         `protobuf:"bytes,3,opt,name=terraform_root,json=terraformRoot,proto3" json:"terraform_root,omitempty"`
	LogLevel      TerraformPluginConfig_LogLevel `protobuf:"varint,4,opt,name=log_level,json=logLevel,proto3,enum=protoconf_terraform.config.v1.TerraformPluginConfig_LogLevel" json:"log_level,omitempty"`
	LogAsJson     bool                           `protobuf:"varint,5,opt,name=log_as_json,json=logAsJson,proto3" json:"log_as_json,omitempty"`
}

func (x *TerraformPluginConfig) Reset() {
	*x = TerraformPluginConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerraformPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerraformPluginConfig) ProtoMessage() {}

func (x *TerraformPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerraformPluginConfig.ProtoReflect.Descriptor instead.
func (*TerraformPluginConfig) Descriptor() ([]byte, []int) {
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *TerraformPluginConfig) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *TerraformPluginConfig) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *TerraformPluginConfig) GetTerraformRoot() string {
	if x != nil {
		return x.TerraformRoot
	}
	return ""
}

func (x *TerraformPluginConfig) GetLogLevel() TerraformPluginConfig_LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return TerraformPluginConfig_LOG_LEVEL_UNSPECIFIED
}

func (x *TerraformPluginConfig) GetLogAsJson() bool {
	if x != nil {
		return x.LogAsJson
	}
	return false
}

type SubscriptionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SubscriptionConfig) Reset() {
	*x = SubscriptionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionConfig) ProtoMessage() {}

func (x *SubscriptionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionConfig.ProtoReflect.Descriptor instead.
func (*SubscriptionConfig) Descriptor() ([]byte, []int) {
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionConfig) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_proto_protoconf_terraform_config_v1_config_proto protoreflect.FileDescriptor

var file_proto_protoconf_terraform_config_v1_config_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e,
	0x66, 0x5f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x74, 0x65,
	0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76,
	0x31, 0x22, 0xa4, 0x03, 0x0a, 0x15, 0x54, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2d, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x65, 0x72,
	0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x5a, 0x0a, 0x09, 0x6c, 0x6f,
	0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65,
	0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x08, 0x6c, 0x6f,
	0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x5f, 0x61, 0x73,
	0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6c, 0x6f, 0x67,
	0x41, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x54, 0x52, 0x41, 0x43,
	0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c,
	0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x5f,
	0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e,
	0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x04,
	0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x06, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6e, 0x66, 0x2d, 0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x74,
	0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f,
	0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_protoconf_terraform_config_v1_config_proto_rawDescOnce sync.Once
	file_proto_protoconf_terraform_config_v1_config_proto_rawDescData = file_proto_protoconf_terraform_config_v1_config_proto_rawDesc
)

func file_proto_protoconf_terraform_config_v1_config_proto_rawDescGZIP() []byte {
	file_proto_protoconf_terraform_config_v1_config_proto_rawDescOnce.Do(func() {
		file_proto_protoconf_terraform_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_protoconf_terraform_config_v1_config_proto_rawDescData)
	})
	return file_proto_protoconf_terraform_config_v1_config_proto_rawDescData
}

var file_proto_protoconf_terraform_config_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_protoconf_terraform_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_protoconf_terraform_config_v1_config_proto_goTypes = []interface{}{
	(TerraformPluginConfig_LogLevel)(0), // 0: protoconf_terraform.config.v1.TerraformPluginConfig.LogLevel
	(*TerraformPluginConfig)(nil),       // 1: protoconf_terraform.config.v1.TerraformPluginConfig
	(*SubscriptionConfig)(nil),          // 2: protoconf_terraform.config.v1.SubscriptionConfig
}
var file_proto_protoconf_terraform_config_v1_config_proto_depIdxs = []int32{
	0, // 0: protoconf_terraform.config.v1.TerraformPluginConfig.log_level:type_name -> protoconf_terraform.config.v1.TerraformPluginConfig.LogLevel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_protoconf_terraform_config_v1_config_proto_init() }
func file_proto_protoconf_terraform_config_v1_config_proto_init() {
	if File_proto_protoconf_terraform_config_v1_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerraformPluginConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_protoconf_terraform_config_v1_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_protoconf_terraform_config_v1_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_protoconf_terraform_config_v1_config_proto_goTypes,
		DependencyIndexes: file_proto_protoconf_terraform_config_v1_config_proto_depIdxs,
		EnumInfos:         file_proto_protoconf_terraform_config_v1_config_proto_enumTypes,
		MessageInfos:      file_proto_protoconf_terraform_config_v1_config_proto_msgTypes,
	}.Build()
	File_proto_protoconf_terraform_config_v1_config_proto = out.File
	file_proto_protoconf_terraform_config_v1_config_proto_rawDesc = nil
	file_proto_protoconf_terraform_config_v1_config_proto_goTypes = nil
	file_proto_protoconf_terraform_config_v1_config_proto_depIdxs = nil
}
