syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsAlb version is 0
message AwsAlb {
  string arn = 1;

  string arn_suffix = 2 [json_name = "arn_suffix"];

  int64 client_keep_alive = 3 [json_name = "client_keep_alive"];

  string customer_owned_ipv4_pool = 4 [json_name = "customer_owned_ipv4_pool"];

  string desync_mitigation_mode = 5 [json_name = "desync_mitigation_mode"];

  string dns_name = 6 [json_name = "dns_name"];

  string dns_record_client_routing_policy = 7 [json_name = "dns_record_client_routing_policy"];

  bool drop_invalid_header_fields = 8 [json_name = "drop_invalid_header_fields"];

  bool enable_cross_zone_load_balancing = 9 [json_name = "enable_cross_zone_load_balancing"];

  bool enable_deletion_protection = 10 [json_name = "enable_deletion_protection"];

  bool enable_http2 = 11 [json_name = "enable_http2"];

  bool enable_tls_version_and_cipher_suite_headers = 12 [
    json_name = "enable_tls_version_and_cipher_suite_headers"
  ];

  bool enable_waf_fail_open = 13 [json_name = "enable_waf_fail_open"];

  bool enable_xff_client_port = 14 [json_name = "enable_xff_client_port"];

  bool enable_zonal_shift = 15 [json_name = "enable_zonal_shift"];

  string enforce_security_group_inbound_rules_on_private_link_traffic = 16 [
    json_name = "enforce_security_group_inbound_rules_on_private_link_traffic"
  ];

  string id = 17;

  int64 idle_timeout = 18 [json_name = "idle_timeout"];

  bool internal = 19;

  string ip_address_type = 20 [json_name = "ip_address_type"];

  string load_balancer_type = 21 [json_name = "load_balancer_type"];

  string name = 22;

  string name_prefix = 23 [json_name = "name_prefix"];

  bool preserve_host_header = 24 [json_name = "preserve_host_header"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 25;

  int64 secondary_ips_auto_assigned_per_subnet = 26 [
    json_name = "secondary_ips_auto_assigned_per_subnet"
  ];

  repeated string security_groups = 27 [json_name = "security_groups"];

  repeated string subnets = 28;

  map<string, string> tags = 29;

  map<string, string> tags_all = 30 [json_name = "tags_all"];

  string vpc_id = 31 [json_name = "vpc_id"];

  string xff_header_processing_mode = 32 [json_name = "xff_header_processing_mode"];

  string zone_id = 33 [json_name = "zone_id"];

  AccessLogs access_logs = 34 [json_name = "access_logs"];

  ConnectionLogs connection_logs = 35 [json_name = "connection_logs"];

  HealthCheckLogs health_check_logs = 36 [json_name = "health_check_logs"];

  IpamPools ipam_pools = 37 [json_name = "ipam_pools"];

  MinimumLoadBalancerCapacity minimum_load_balancer_capacity = 38 [json_name = "minimum_load_balancer_capacity"];

  repeated SubnetMapping subnet_mapping = 39 [json_name = "subnet_mapping"];

  repeated Timeouts timeouts = 40;

  google.protobuf.Value for_each = 41 [json_name = "for_each"];

  repeated string depends_on = 42 [json_name = "depends_on"];

  int32 count = 43;

  string provider = 44;

  terraform.v1.Lifecycle lifecycle = 45;

  message AccessLogs {
    string bucket = 1;

    bool enabled = 2;

    string prefix = 3;
  }

  message ConnectionLogs {
    string bucket = 1;

    bool enabled = 2;

    string prefix = 3;
  }

  message HealthCheckLogs {
    string bucket = 1;

    bool enabled = 2;

    string prefix = 3;
  }

  message IpamPools {
    string ipv4_ipam_pool_id = 1 [json_name = "ipv4_ipam_pool_id"];
  }

  message MinimumLoadBalancerCapacity {
    int64 capacity_units = 1 [json_name = "capacity_units"];
  }

  message SubnetMapping {
    string allocation_id = 1 [json_name = "allocation_id"];

    string ipv6_address = 2 [json_name = "ipv6_address"];

    string outpost_id = 3 [json_name = "outpost_id"];

    string private_ipv4_address = 4 [json_name = "private_ipv4_address"];

    string subnet_id = 5 [json_name = "subnet_id"];
  }

  message Timeouts {
    string create = 1;

    string delete = 2;

    string update = 3;
  }
}

// AwsAlbListener version is 0
message AwsAlbListener {
  string alpn_policy = 1 [json_name = "alpn_policy"];

  string arn = 2;

  string certificate_arn = 3 [json_name = "certificate_arn"];

  string id = 4;

  string load_balancer_arn = 5 [json_name = "load_balancer_arn"];

  int64 port = 6;

  string protocol = 7;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 8;

  string routing_http_request_x_amzn_mtls_clientcert_header_name = 9 [
    json_name = "routing_http_request_x_amzn_mtls_clientcert_header_name"
  ];

  string routing_http_request_x_amzn_mtls_clientcert_issuer_header_name = 10 [
    json_name = "routing_http_request_x_amzn_mtls_clientcert_issuer_header_name"
  ];

  string routing_http_request_x_amzn_mtls_clientcert_leaf_header_name = 11 [
    json_name = "routing_http_request_x_amzn_mtls_clientcert_leaf_header_name"
  ];

  string routing_http_request_x_amzn_mtls_clientcert_serial_number_header_name = 12 [
    json_name = "routing_http_request_x_amzn_mtls_clientcert_serial_number_header_name"
  ];

  string routing_http_request_x_amzn_mtls_clientcert_subject_header_name = 13 [
    json_name = "routing_http_request_x_amzn_mtls_clientcert_subject_header_name"
  ];

  string routing_http_request_x_amzn_mtls_clientcert_validity_header_name = 14 [
    json_name = "routing_http_request_x_amzn_mtls_clientcert_validity_header_name"
  ];

  string routing_http_request_x_amzn_tls_cipher_suite_header_name = 15 [
    json_name = "routing_http_request_x_amzn_tls_cipher_suite_header_name"
  ];

  string routing_http_request_x_amzn_tls_version_header_name = 16 [
    json_name = "routing_http_request_x_amzn_tls_version_header_name"
  ];

  string routing_http_response_access_control_allow_credentials_header_value = 17 [
    json_name = "routing_http_response_access_control_allow_credentials_header_value"
  ];

  string routing_http_response_access_control_allow_headers_header_value = 18 [
    json_name = "routing_http_response_access_control_allow_headers_header_value"
  ];

  string routing_http_response_access_control_allow_methods_header_value = 19 [
    json_name = "routing_http_response_access_control_allow_methods_header_value"
  ];

  string routing_http_response_access_control_allow_origin_header_value = 20 [
    json_name = "routing_http_response_access_control_allow_origin_header_value"
  ];

  string routing_http_response_access_control_expose_headers_header_value = 21 [
    json_name = "routing_http_response_access_control_expose_headers_header_value"
  ];

  string routing_http_response_access_control_max_age_header_value = 22 [
    json_name = "routing_http_response_access_control_max_age_header_value"
  ];

  string routing_http_response_content_security_policy_header_value = 23 [
    json_name = "routing_http_response_content_security_policy_header_value"
  ];

  bool routing_http_response_server_enabled = 24 [json_name = "routing_http_response_server_enabled"];

  string routing_http_response_strict_transport_security_header_value = 25 [
    json_name = "routing_http_response_strict_transport_security_header_value"
  ];

  string routing_http_response_x_content_type_options_header_value = 26 [
    json_name = "routing_http_response_x_content_type_options_header_value"
  ];

  string routing_http_response_x_frame_options_header_value = 27 [
    json_name = "routing_http_response_x_frame_options_header_value"
  ];

  string ssl_policy = 28 [json_name = "ssl_policy"];

  map<string, string> tags = 29;

  map<string, string> tags_all = 30 [json_name = "tags_all"];

  int64 tcp_idle_timeout_seconds = 31 [json_name = "tcp_idle_timeout_seconds"];

  repeated DefaultAction default_action = 32 [json_name = "default_action"];

  MutualAuthentication mutual_authentication = 33 [json_name = "mutual_authentication"];

  repeated Timeouts timeouts = 34;

  google.protobuf.Value for_each = 35 [json_name = "for_each"];

  repeated string depends_on = 36 [json_name = "depends_on"];

  int32 count = 37;

  string provider = 38;

  terraform.v1.Lifecycle lifecycle = 39;

  message DefaultAction {
    int64 order = 1;

    string target_group_arn = 2 [json_name = "target_group_arn"];

    string type = 3;

    AuthenticateCognito authenticate_cognito = 4 [json_name = "authenticate_cognito"];

    AuthenticateOidc authenticate_oidc = 5 [json_name = "authenticate_oidc"];

    FixedResponse fixed_response = 6 [json_name = "fixed_response"];

    Forward forward = 7;

    JwtValidation jwt_validation = 8 [json_name = "jwt_validation"];

    Redirect redirect = 9;

    message AuthenticateCognito {
      map<string, string> authentication_request_extra_params = 1 [json_name = "authentication_request_extra_params"];

      string on_unauthenticated_request = 2 [json_name = "on_unauthenticated_request"];

      string scope = 3;

      string session_cookie_name = 4 [json_name = "session_cookie_name"];

      int64 session_timeout = 5 [json_name = "session_timeout"];

      string user_pool_arn = 6 [json_name = "user_pool_arn"];

      string user_pool_client_id = 7 [json_name = "user_pool_client_id"];

      string user_pool_domain = 8 [json_name = "user_pool_domain"];
    }

    message AuthenticateOidc {
      map<string, string> authentication_request_extra_params = 1 [json_name = "authentication_request_extra_params"];

      string authorization_endpoint = 2 [json_name = "authorization_endpoint"];

      string client_id = 3 [json_name = "client_id"];

      string client_secret = 4 [json_name = "client_secret"];

      string issuer = 5;

      string on_unauthenticated_request = 6 [json_name = "on_unauthenticated_request"];

      string scope = 7;

      string session_cookie_name = 8 [json_name = "session_cookie_name"];

      int64 session_timeout = 9 [json_name = "session_timeout"];

      string token_endpoint = 10 [json_name = "token_endpoint"];

      string user_info_endpoint = 11 [json_name = "user_info_endpoint"];
    }

    message FixedResponse {
      string content_type = 1 [json_name = "content_type"];

      string message_body = 2 [json_name = "message_body"];

      string status_code = 3 [json_name = "status_code"];
    }

    message Forward {
      Stickiness stickiness = 1;

      repeated TargetGroup target_group = 2 [json_name = "target_group"];

      message Stickiness {
        int64 duration = 1;

        bool enabled = 2;
      }

      message TargetGroup {
        string arn = 1;

        int64 weight = 2;
      }
    }

    message JwtValidation {
      string issuer = 1;

      string jwks_endpoint = 2 [json_name = "jwks_endpoint"];

      repeated AdditionalClaim additional_claim = 3 [json_name = "additional_claim"];

      message AdditionalClaim {
        string format = 1;

        string name = 2;

        repeated string values = 3;
      }
    }

    message Redirect {
      string host = 1;

      string path = 2;

      string port = 3;

      string protocol = 4;

      string query = 5;

      string status_code = 6 [json_name = "status_code"];
    }
  }

  message MutualAuthentication {
    string advertise_trust_store_ca_names = 1 [json_name = "advertise_trust_store_ca_names"];

    bool ignore_client_certificate_expiry = 2 [json_name = "ignore_client_certificate_expiry"];

    string mode = 3;

    string trust_store_arn = 4 [json_name = "trust_store_arn"];
  }

  message Timeouts {
    string create = 1;

    string update = 2;
  }
}

// AwsAlbListenerCertificate version is 0
message AwsAlbListenerCertificate {
  string certificate_arn = 1 [json_name = "certificate_arn"];

  string id = 2;

  string listener_arn = 3 [json_name = "listener_arn"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsAlbListenerRule version is 0
message AwsAlbListenerRule {
  string arn = 1;

  string id = 2;

  string listener_arn = 3 [json_name = "listener_arn"];

  int64 priority = 4;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  map<string, string> tags = 6;

  map<string, string> tags_all = 7 [json_name = "tags_all"];

  repeated Action action = 8;

  repeated Condition condition = 9;

  repeated Transform transform = 10;

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message Action {
    int64 order = 1;

    string target_group_arn = 2 [json_name = "target_group_arn"];

    string type = 3;

    AuthenticateCognito authenticate_cognito = 4 [json_name = "authenticate_cognito"];

    AuthenticateOidc authenticate_oidc = 5 [json_name = "authenticate_oidc"];

    FixedResponse fixed_response = 6 [json_name = "fixed_response"];

    Forward forward = 7;

    JwtValidation jwt_validation = 8 [json_name = "jwt_validation"];

    Redirect redirect = 9;

    message AuthenticateCognito {
      map<string, string> authentication_request_extra_params = 1 [json_name = "authentication_request_extra_params"];

      string on_unauthenticated_request = 2 [json_name = "on_unauthenticated_request"];

      string scope = 3;

      string session_cookie_name = 4 [json_name = "session_cookie_name"];

      int64 session_timeout = 5 [json_name = "session_timeout"];

      string user_pool_arn = 6 [json_name = "user_pool_arn"];

      string user_pool_client_id = 7 [json_name = "user_pool_client_id"];

      string user_pool_domain = 8 [json_name = "user_pool_domain"];
    }

    message AuthenticateOidc {
      map<string, string> authentication_request_extra_params = 1 [json_name = "authentication_request_extra_params"];

      string authorization_endpoint = 2 [json_name = "authorization_endpoint"];

      string client_id = 3 [json_name = "client_id"];

      string client_secret = 4 [json_name = "client_secret"];

      string issuer = 5;

      string on_unauthenticated_request = 6 [json_name = "on_unauthenticated_request"];

      string scope = 7;

      string session_cookie_name = 8 [json_name = "session_cookie_name"];

      int64 session_timeout = 9 [json_name = "session_timeout"];

      string token_endpoint = 10 [json_name = "token_endpoint"];

      string user_info_endpoint = 11 [json_name = "user_info_endpoint"];
    }

    message FixedResponse {
      string content_type = 1 [json_name = "content_type"];

      string message_body = 2 [json_name = "message_body"];

      string status_code = 3 [json_name = "status_code"];
    }

    message Forward {
      Stickiness stickiness = 1;

      repeated TargetGroup target_group = 2 [json_name = "target_group"];

      message Stickiness {
        int64 duration = 1;

        bool enabled = 2;
      }

      message TargetGroup {
        string arn = 1;

        int64 weight = 2;
      }
    }

    message JwtValidation {
      string issuer = 1;

      string jwks_endpoint = 2 [json_name = "jwks_endpoint"];

      repeated AdditionalClaim additional_claim = 3 [json_name = "additional_claim"];

      message AdditionalClaim {
        string format = 1;

        string name = 2;

        repeated string values = 3;
      }
    }

    message Redirect {
      string host = 1;

      string path = 2;

      string port = 3;

      string protocol = 4;

      string query = 5;

      string status_code = 6 [json_name = "status_code"];
    }
  }

  message Condition {
    HostHeader host_header = 1 [json_name = "host_header"];

    HttpHeader http_header = 2 [json_name = "http_header"];

    HttpRequestMethod http_request_method = 3 [json_name = "http_request_method"];

    PathPattern path_pattern = 4 [json_name = "path_pattern"];

    repeated QueryString query_string = 5 [json_name = "query_string"];

    SourceIp source_ip = 6 [json_name = "source_ip"];

    message HostHeader {
      repeated string regex_values = 1 [json_name = "regex_values"];

      repeated string values = 2;
    }

    message HttpHeader {
      string http_header_name = 1 [json_name = "http_header_name"];

      repeated string regex_values = 2 [json_name = "regex_values"];

      repeated string values = 3;
    }

    message HttpRequestMethod {
      repeated string values = 1;
    }

    message PathPattern {
      repeated string regex_values = 1 [json_name = "regex_values"];

      repeated string values = 2;
    }

    message QueryString {
      string key = 1;

      string value = 2;
    }

    message SourceIp {
      repeated string values = 1;
    }
  }

  message Transform {
    string type = 1;

    HostHeaderRewriteConfig host_header_rewrite_config = 2 [json_name = "host_header_rewrite_config"];

    UrlRewriteConfig url_rewrite_config = 3 [json_name = "url_rewrite_config"];

    message HostHeaderRewriteConfig {
      Rewrite rewrite = 1;

      message Rewrite {
        string regex = 1;

        string replace = 2;
      }
    }

    message UrlRewriteConfig {
      Rewrite rewrite = 1;

      message Rewrite {
        string regex = 1;

        string replace = 2;
      }
    }
  }
}

// AwsAlbTargetGroup version is 0
message AwsAlbTargetGroup {
  string arn = 1;

  string arn_suffix = 2 [json_name = "arn_suffix"];

  bool connection_termination = 3 [json_name = "connection_termination"];

  string deregistration_delay = 4 [json_name = "deregistration_delay"];

  string id = 5;

  string ip_address_type = 6 [json_name = "ip_address_type"];

  bool lambda_multi_value_headers_enabled = 7 [json_name = "lambda_multi_value_headers_enabled"];

  repeated string load_balancer_arns = 8 [json_name = "load_balancer_arns"];

  string load_balancing_algorithm_type = 9 [json_name = "load_balancing_algorithm_type"];

  string load_balancing_anomaly_mitigation = 10 [json_name = "load_balancing_anomaly_mitigation"];

  string load_balancing_cross_zone_enabled = 11 [json_name = "load_balancing_cross_zone_enabled"];

  string name = 12;

  string name_prefix = 13 [json_name = "name_prefix"];

  int64 port = 14;

  string preserve_client_ip = 15 [json_name = "preserve_client_ip"];

  string protocol = 16;

  string protocol_version = 17 [json_name = "protocol_version"];

  bool proxy_protocol_v2 = 18 [json_name = "proxy_protocol_v2"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 19;

  int64 slow_start = 20 [json_name = "slow_start"];

  map<string, string> tags = 21;

  map<string, string> tags_all = 22 [json_name = "tags_all"];

  int64 target_control_port = 23 [json_name = "target_control_port"];

  string target_type = 24 [json_name = "target_type"];

  string vpc_id = 25 [json_name = "vpc_id"];

  HealthCheck health_check = 26 [json_name = "health_check"];

  Stickiness stickiness = 27;

  repeated TargetFailover target_failover = 28 [json_name = "target_failover"];

  TargetGroupHealth target_group_health = 29 [json_name = "target_group_health"];

  repeated TargetHealthState target_health_state = 30 [json_name = "target_health_state"];

  google.protobuf.Value for_each = 31 [json_name = "for_each"];

  repeated string depends_on = 32 [json_name = "depends_on"];

  int32 count = 33;

  string provider = 34;

  terraform.v1.Lifecycle lifecycle = 35;

  message HealthCheck {
    bool enabled = 1;

    int64 healthy_threshold = 2 [json_name = "healthy_threshold"];

    int64 interval = 3;

    string matcher = 4;

    string path = 5;

    string port = 6;

    string protocol = 7;

    int64 timeout = 8;

    int64 unhealthy_threshold = 9 [json_name = "unhealthy_threshold"];
  }

  message Stickiness {
    int64 cookie_duration = 1 [json_name = "cookie_duration"];

    string cookie_name = 2 [json_name = "cookie_name"];

    bool enabled = 3;

    string type = 4;
  }

  message TargetFailover {
    string on_deregistration = 1 [json_name = "on_deregistration"];

    string on_unhealthy = 2 [json_name = "on_unhealthy"];
  }

  message TargetGroupHealth {
    DnsFailover dns_failover = 1 [json_name = "dns_failover"];

    UnhealthyStateRouting unhealthy_state_routing = 2 [json_name = "unhealthy_state_routing"];

    message DnsFailover {
      string minimum_healthy_targets_count = 1 [json_name = "minimum_healthy_targets_count"];

      string minimum_healthy_targets_percentage = 2 [json_name = "minimum_healthy_targets_percentage"];
    }

    message UnhealthyStateRouting {
      int64 minimum_healthy_targets_count = 1 [json_name = "minimum_healthy_targets_count"];

      string minimum_healthy_targets_percentage = 2 [json_name = "minimum_healthy_targets_percentage"];
    }
  }

  message TargetHealthState {
    bool enable_unhealthy_connection_termination = 1 [
      json_name = "enable_unhealthy_connection_termination"
    ];

    int64 unhealthy_draining_interval = 2 [json_name = "unhealthy_draining_interval"];
  }
}

// AwsAlbTargetGroupAttachment version is 0
message AwsAlbTargetGroupAttachment {
  string availability_zone = 1 [json_name = "availability_zone"];

  string id = 2;

  int64 port = 3;

  string quic_server_id = 4 [json_name = "quic_server_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  string target_group_arn = 6 [json_name = "target_group_arn"];

  string target_id = 7 [json_name = "target_id"];

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;
}
