syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsCodecommitApprovalRuleTemplate version is 0
message AwsCodecommitApprovalRuleTemplate {
  string approval_rule_template_id = 1 [json_name = "approval_rule_template_id"];

  string content = 2;

  string creation_date = 3 [json_name = "creation_date"];

  string description = 4;

  string id = 5;

  string last_modified_date = 6 [json_name = "last_modified_date"];

  string last_modified_user = 7 [json_name = "last_modified_user"];

  string name = 8;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 9;

  string rule_content_sha256 = 10 [json_name = "rule_content_sha256"];

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;
}

// AwsCodecommitApprovalRuleTemplateAssociation version is 0
message AwsCodecommitApprovalRuleTemplateAssociation {
  string approval_rule_template_name = 1 [json_name = "approval_rule_template_name"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  string repository_name = 4 [json_name = "repository_name"];

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsCodecommitRepository version is 0
message AwsCodecommitRepository {
  string arn = 1;

  string clone_url_http = 2 [json_name = "clone_url_http"];

  string clone_url_ssh = 3 [json_name = "clone_url_ssh"];

  string default_branch = 4 [json_name = "default_branch"];

  string description = 5;

  string id = 6;

  string kms_key_id = 7 [json_name = "kms_key_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 8;

  string repository_id = 9 [json_name = "repository_id"];

  string repository_name = 10 [json_name = "repository_name"];

  map<string, string> tags = 11;

  map<string, string> tags_all = 12 [json_name = "tags_all"];

  google.protobuf.Value for_each = 13 [json_name = "for_each"];

  repeated string depends_on = 14 [json_name = "depends_on"];

  int32 count = 15;

  string provider = 16;

  terraform.v1.Lifecycle lifecycle = 17;
}

// AwsCodecommitTrigger version is 0
message AwsCodecommitTrigger {
  string configuration_id = 1 [json_name = "configuration_id"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  string repository_name = 4 [json_name = "repository_name"];

  repeated Trigger trigger = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;

  message Trigger {
    repeated string branches = 1;

    string custom_data = 2 [json_name = "custom_data"];

    string destination_arn = 3 [json_name = "destination_arn"];

    repeated string events = 4;

    string name = 5;
  }
}
