syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsDetectiveGraph version is 0
message AwsDetectiveGraph {
  string created_time = 1 [json_name = "created_time"];

  string graph_arn = 2 [json_name = "graph_arn"];

  string id = 3;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  map<string, string> tags = 5;

  map<string, string> tags_all = 6 [json_name = "tags_all"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// AwsDetectiveInvitationAccepter version is 0
message AwsDetectiveInvitationAccepter {
  string graph_arn = 1 [json_name = "graph_arn"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}

// AwsDetectiveMember version is 0
message AwsDetectiveMember {
  string account_id = 1 [json_name = "account_id"];

  string administrator_id = 2 [json_name = "administrator_id"];

  bool disable_email_notification = 3 [json_name = "disable_email_notification"];

  string disabled_reason = 4 [json_name = "disabled_reason"];

  string email_address = 5 [json_name = "email_address"];

  string graph_arn = 6 [json_name = "graph_arn"];

  string id = 7;

  string invited_time = 8 [json_name = "invited_time"];

  string message = 9;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 10;

  string status = 11;

  string updated_time = 12 [json_name = "updated_time"];

  string volume_usage_in_bytes = 13 [json_name = "volume_usage_in_bytes"];

  google.protobuf.Value for_each = 14 [json_name = "for_each"];

  repeated string depends_on = 15 [json_name = "depends_on"];

  int32 count = 16;

  string provider = 17;

  terraform.v1.Lifecycle lifecycle = 18;
}

// AwsDetectiveOrganizationAdminAccount version is 0
message AwsDetectiveOrganizationAdminAccount {
  string account_id = 1 [json_name = "account_id"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}

// AwsDetectiveOrganizationConfiguration version is 0
message AwsDetectiveOrganizationConfiguration {
  bool auto_enable = 1 [json_name = "auto_enable"];

  string graph_arn = 2 [json_name = "graph_arn"];

  string id = 3;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}
