syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsEmrBlockPublicAccessConfiguration version is 0
message AwsEmrBlockPublicAccessConfiguration {
  bool block_public_security_group_rules = 1 [json_name = "block_public_security_group_rules"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  repeated PermittedPublicSecurityGroupRuleRange permitted_public_security_group_rule_range = 4 [
    json_name = "permitted_public_security_group_rule_range"
  ];

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;

  message PermittedPublicSecurityGroupRuleRange {
    int64 max_range = 1 [json_name = "max_range"];

    int64 min_range = 2 [json_name = "min_range"];
  }
}

// AwsEmrCluster version is 0
message AwsEmrCluster {
  string additional_info = 1 [json_name = "additional_info"];

  repeated string applications = 2;

  string arn = 3;

  string autoscaling_role = 4 [json_name = "autoscaling_role"];

  string cluster_state = 5 [json_name = "cluster_state"];

  string configurations = 6;

  string configurations_json = 7 [json_name = "configurations_json"];

  string custom_ami_id = 8 [json_name = "custom_ami_id"];

  int64 ebs_root_volume_size = 9 [json_name = "ebs_root_volume_size"];

  string id = 10;

  bool keep_job_flow_alive_when_no_steps = 11 [json_name = "keep_job_flow_alive_when_no_steps"];

  repeated string list_steps_states = 12 [json_name = "list_steps_states"];

  string log_encryption_kms_key_id = 13 [json_name = "log_encryption_kms_key_id"];

  string log_uri = 14 [json_name = "log_uri"];

  string master_public_dns = 15 [json_name = "master_public_dns"];

  string name = 16;

  string os_release_label = 17 [json_name = "os_release_label"];

  repeated PlacementGroupConfig placement_group_config = 18 [json_name = "placement_group_config"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 19;

  string release_label = 20 [json_name = "release_label"];

  string scale_down_behavior = 21 [json_name = "scale_down_behavior"];

  string security_configuration = 22 [json_name = "security_configuration"];

  string service_role = 23 [json_name = "service_role"];

  repeated Step step = 24;

  int64 step_concurrency_level = 25 [json_name = "step_concurrency_level"];

  map<string, string> tags = 26;

  map<string, string> tags_all = 27 [json_name = "tags_all"];

  bool termination_protection = 28 [json_name = "termination_protection"];

  bool unhealthy_node_replacement = 29 [json_name = "unhealthy_node_replacement"];

  bool visible_to_all_users = 30 [json_name = "visible_to_all_users"];

  AutoTerminationPolicy auto_termination_policy = 31 [json_name = "auto_termination_policy"];

  repeated BootstrapAction bootstrap_action = 32 [json_name = "bootstrap_action"];

  CoreInstanceFleet core_instance_fleet = 33 [json_name = "core_instance_fleet"];

  CoreInstanceGroup core_instance_group = 34 [json_name = "core_instance_group"];

  Ec2Attributes ec2_attributes = 35 [json_name = "ec2_attributes"];

  KerberosAttributes kerberos_attributes = 36 [json_name = "kerberos_attributes"];

  MasterInstanceFleet master_instance_fleet = 37 [json_name = "master_instance_fleet"];

  MasterInstanceGroup master_instance_group = 38 [json_name = "master_instance_group"];

  google.protobuf.Value for_each = 39 [json_name = "for_each"];

  repeated string depends_on = 40 [json_name = "depends_on"];

  int32 count = 41;

  string provider = 42;

  terraform.v1.Lifecycle lifecycle = 43;

  message PlacementGroupConfig {
    // instance_role: string
    string instance_role = 1 [json_name = "instance_role"];

    // placement_strategy: string
    string placement_strategy = 2 [json_name = "placement_strategy"];
  }

  message Step {
    // action_on_failure: string
    string action_on_failure = 1 [json_name = "action_on_failure"];

    // hadoop_jar_step: list of object
    repeated HadoopJarStep hadoop_jar_step = 2 [json_name = "hadoop_jar_step"];

    // name: string
    string name = 3;

    message HadoopJarStep {
      // args: list of string
      repeated string args = 1;

      // jar: string
      string jar = 2;

      // main_class: string
      string main_class = 3 [json_name = "main_class"];

      // properties: map of string
      map<string, string> properties = 4;
    }
  }

  message AutoTerminationPolicy {
    int64 idle_timeout = 1 [json_name = "idle_timeout"];
  }

  message BootstrapAction {
    repeated string args = 1;

    string name = 2;

    string path = 3;
  }

  message CoreInstanceFleet {
    string id = 1;

    string name = 2;

    int64 provisioned_on_demand_capacity = 3 [json_name = "provisioned_on_demand_capacity"];

    int64 provisioned_spot_capacity = 4 [json_name = "provisioned_spot_capacity"];

    int64 target_on_demand_capacity = 5 [json_name = "target_on_demand_capacity"];

    int64 target_spot_capacity = 6 [json_name = "target_spot_capacity"];

    repeated InstanceTypeConfigs instance_type_configs = 7 [json_name = "instance_type_configs"];

    LaunchSpecifications launch_specifications = 8 [json_name = "launch_specifications"];

    message InstanceTypeConfigs {
      string bid_price = 1 [json_name = "bid_price"];

      int64 bid_price_as_percentage_of_on_demand_price = 2 [
        json_name = "bid_price_as_percentage_of_on_demand_price"
      ];

      string instance_type = 3 [json_name = "instance_type"];

      int64 weighted_capacity = 4 [json_name = "weighted_capacity"];

      repeated Configurations configurations = 5;

      repeated EbsConfig ebs_config = 6 [json_name = "ebs_config"];

      message Configurations {
        string classification = 1;

        map<string, string> properties = 2;
      }

      message EbsConfig {
        int64 iops = 1;

        int64 size = 2;

        string type = 3;

        int64 volumes_per_instance = 4 [json_name = "volumes_per_instance"];
      }
    }

    message LaunchSpecifications {
      repeated OnDemandSpecification on_demand_specification = 1 [json_name = "on_demand_specification"];

      repeated SpotSpecification spot_specification = 2 [json_name = "spot_specification"];

      message OnDemandSpecification {
        string allocation_strategy = 1 [json_name = "allocation_strategy"];
      }

      message SpotSpecification {
        string allocation_strategy = 1 [json_name = "allocation_strategy"];

        int64 block_duration_minutes = 2 [json_name = "block_duration_minutes"];

        string timeout_action = 3 [json_name = "timeout_action"];

        int64 timeout_duration_minutes = 4 [json_name = "timeout_duration_minutes"];
      }
    }
  }

  message CoreInstanceGroup {
    string autoscaling_policy = 1 [json_name = "autoscaling_policy"];

    string bid_price = 2 [json_name = "bid_price"];

    string id = 3;

    int64 instance_count = 4 [json_name = "instance_count"];

    string instance_type = 5 [json_name = "instance_type"];

    string name = 6;

    repeated EbsConfig ebs_config = 7 [json_name = "ebs_config"];

    message EbsConfig {
      int64 iops = 1;

      int64 size = 2;

      int64 throughput = 3;

      string type = 4;

      int64 volumes_per_instance = 5 [json_name = "volumes_per_instance"];
    }
  }

  message Ec2Attributes {
    string additional_master_security_groups = 1 [json_name = "additional_master_security_groups"];

    string additional_slave_security_groups = 2 [json_name = "additional_slave_security_groups"];

    string emr_managed_master_security_group = 3 [json_name = "emr_managed_master_security_group"];

    string emr_managed_slave_security_group = 4 [json_name = "emr_managed_slave_security_group"];

    string instance_profile = 5 [json_name = "instance_profile"];

    string key_name = 6 [json_name = "key_name"];

    string service_access_security_group = 7 [json_name = "service_access_security_group"];

    string subnet_id = 8 [json_name = "subnet_id"];

    repeated string subnet_ids = 9 [json_name = "subnet_ids"];
  }

  message KerberosAttributes {
    string ad_domain_join_password = 1 [json_name = "ad_domain_join_password"];

    string ad_domain_join_user = 2 [json_name = "ad_domain_join_user"];

    string cross_realm_trust_principal_password = 3 [json_name = "cross_realm_trust_principal_password"];

    string kdc_admin_password = 4 [json_name = "kdc_admin_password"];

    string realm = 5;
  }

  message MasterInstanceFleet {
    string id = 1;

    string name = 2;

    int64 provisioned_on_demand_capacity = 3 [json_name = "provisioned_on_demand_capacity"];

    int64 provisioned_spot_capacity = 4 [json_name = "provisioned_spot_capacity"];

    int64 target_on_demand_capacity = 5 [json_name = "target_on_demand_capacity"];

    int64 target_spot_capacity = 6 [json_name = "target_spot_capacity"];

    repeated InstanceTypeConfigs instance_type_configs = 7 [json_name = "instance_type_configs"];

    LaunchSpecifications launch_specifications = 8 [json_name = "launch_specifications"];

    message InstanceTypeConfigs {
      string bid_price = 1 [json_name = "bid_price"];

      int64 bid_price_as_percentage_of_on_demand_price = 2 [
        json_name = "bid_price_as_percentage_of_on_demand_price"
      ];

      string instance_type = 3 [json_name = "instance_type"];

      int64 weighted_capacity = 4 [json_name = "weighted_capacity"];

      repeated Configurations configurations = 5;

      repeated EbsConfig ebs_config = 6 [json_name = "ebs_config"];

      message Configurations {
        string classification = 1;

        map<string, string> properties = 2;
      }

      message EbsConfig {
        int64 iops = 1;

        int64 size = 2;

        string type = 3;

        int64 volumes_per_instance = 4 [json_name = "volumes_per_instance"];
      }
    }

    message LaunchSpecifications {
      repeated OnDemandSpecification on_demand_specification = 1 [json_name = "on_demand_specification"];

      repeated SpotSpecification spot_specification = 2 [json_name = "spot_specification"];

      message OnDemandSpecification {
        string allocation_strategy = 1 [json_name = "allocation_strategy"];
      }

      message SpotSpecification {
        string allocation_strategy = 1 [json_name = "allocation_strategy"];

        int64 block_duration_minutes = 2 [json_name = "block_duration_minutes"];

        string timeout_action = 3 [json_name = "timeout_action"];

        int64 timeout_duration_minutes = 4 [json_name = "timeout_duration_minutes"];
      }
    }
  }

  message MasterInstanceGroup {
    string bid_price = 1 [json_name = "bid_price"];

    string id = 2;

    int64 instance_count = 3 [json_name = "instance_count"];

    string instance_type = 4 [json_name = "instance_type"];

    string name = 5;

    repeated EbsConfig ebs_config = 6 [json_name = "ebs_config"];

    message EbsConfig {
      int64 iops = 1;

      int64 size = 2;

      int64 throughput = 3;

      string type = 4;

      int64 volumes_per_instance = 5 [json_name = "volumes_per_instance"];
    }
  }
}

// AwsEmrInstanceFleet version is 0
message AwsEmrInstanceFleet {
  string cluster_id = 1 [json_name = "cluster_id"];

  string id = 2;

  string name = 3;

  int64 provisioned_on_demand_capacity = 4 [json_name = "provisioned_on_demand_capacity"];

  int64 provisioned_spot_capacity = 5 [json_name = "provisioned_spot_capacity"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  int64 target_on_demand_capacity = 7 [json_name = "target_on_demand_capacity"];

  int64 target_spot_capacity = 8 [json_name = "target_spot_capacity"];

  repeated InstanceTypeConfigs instance_type_configs = 9 [json_name = "instance_type_configs"];

  LaunchSpecifications launch_specifications = 10 [json_name = "launch_specifications"];

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message InstanceTypeConfigs {
    string bid_price = 1 [json_name = "bid_price"];

    int64 bid_price_as_percentage_of_on_demand_price = 2 [
      json_name = "bid_price_as_percentage_of_on_demand_price"
    ];

    string instance_type = 3 [json_name = "instance_type"];

    int64 weighted_capacity = 4 [json_name = "weighted_capacity"];

    repeated Configurations configurations = 5;

    repeated EbsConfig ebs_config = 6 [json_name = "ebs_config"];

    message Configurations {
      string classification = 1;

      map<string, string> properties = 2;
    }

    message EbsConfig {
      int64 iops = 1;

      int64 size = 2;

      string type = 3;

      int64 volumes_per_instance = 4 [json_name = "volumes_per_instance"];
    }
  }

  message LaunchSpecifications {
    repeated OnDemandSpecification on_demand_specification = 1 [json_name = "on_demand_specification"];

    repeated SpotSpecification spot_specification = 2 [json_name = "spot_specification"];

    message OnDemandSpecification {
      string allocation_strategy = 1 [json_name = "allocation_strategy"];
    }

    message SpotSpecification {
      string allocation_strategy = 1 [json_name = "allocation_strategy"];

      int64 block_duration_minutes = 2 [json_name = "block_duration_minutes"];

      string timeout_action = 3 [json_name = "timeout_action"];

      int64 timeout_duration_minutes = 4 [json_name = "timeout_duration_minutes"];
    }
  }
}

// AwsEmrInstanceGroup version is 0
message AwsEmrInstanceGroup {
  string autoscaling_policy = 1 [json_name = "autoscaling_policy"];

  string bid_price = 2 [json_name = "bid_price"];

  string cluster_id = 3 [json_name = "cluster_id"];

  string configurations_json = 4 [json_name = "configurations_json"];

  bool ebs_optimized = 5 [json_name = "ebs_optimized"];

  string id = 6;

  int64 instance_count = 7 [json_name = "instance_count"];

  string instance_type = 8 [json_name = "instance_type"];

  string name = 9;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 10;

  int64 running_instance_count = 11 [json_name = "running_instance_count"];

  string status = 12;

  repeated EbsConfig ebs_config = 13 [json_name = "ebs_config"];

  google.protobuf.Value for_each = 14 [json_name = "for_each"];

  repeated string depends_on = 15 [json_name = "depends_on"];

  int32 count = 16;

  string provider = 17;

  terraform.v1.Lifecycle lifecycle = 18;

  message EbsConfig {
    int64 iops = 1;

    int64 size = 2;

    string type = 3;

    int64 volumes_per_instance = 4 [json_name = "volumes_per_instance"];
  }
}

// AwsEmrManagedScalingPolicy version is 0
message AwsEmrManagedScalingPolicy {
  string cluster_id = 1 [json_name = "cluster_id"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  string scaling_strategy = 4 [json_name = "scaling_strategy"];

  int64 utilization_performance_index = 5 [json_name = "utilization_performance_index"];

  repeated ComputeLimits compute_limits = 6 [json_name = "compute_limits"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;

  message ComputeLimits {
    int64 maximum_capacity_units = 1 [json_name = "maximum_capacity_units"];

    int64 maximum_core_capacity_units = 2 [json_name = "maximum_core_capacity_units"];

    int64 maximum_ondemand_capacity_units = 3 [json_name = "maximum_ondemand_capacity_units"];

    int64 minimum_capacity_units = 4 [json_name = "minimum_capacity_units"];

    string unit_type = 5 [json_name = "unit_type"];
  }
}

// AwsEmrSecurityConfiguration version is 0
message AwsEmrSecurityConfiguration {
  string configuration = 1;

  string creation_date = 2 [json_name = "creation_date"];

  string id = 3;

  string name = 4;

  string name_prefix = 5 [json_name = "name_prefix"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// AwsEmrStudio version is 0
message AwsEmrStudio {
  string arn = 1;

  string auth_mode = 2 [json_name = "auth_mode"];

  string default_s3_location = 3 [json_name = "default_s3_location"];

  string description = 4;

  string encryption_key_arn = 5 [json_name = "encryption_key_arn"];

  string engine_security_group_id = 6 [json_name = "engine_security_group_id"];

  string id = 7;

  string idp_auth_url = 8 [json_name = "idp_auth_url"];

  string idp_relay_state_parameter_name = 9 [json_name = "idp_relay_state_parameter_name"];

  string name = 10;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 11;

  string service_role = 12 [json_name = "service_role"];

  repeated string subnet_ids = 13 [json_name = "subnet_ids"];

  map<string, string> tags = 14;

  map<string, string> tags_all = 15 [json_name = "tags_all"];

  string url = 16;

  string user_role = 17 [json_name = "user_role"];

  string vpc_id = 18 [json_name = "vpc_id"];

  string workspace_security_group_id = 19 [json_name = "workspace_security_group_id"];

  google.protobuf.Value for_each = 20 [json_name = "for_each"];

  repeated string depends_on = 21 [json_name = "depends_on"];

  int32 count = 22;

  string provider = 23;

  terraform.v1.Lifecycle lifecycle = 24;
}

// AwsEmrStudioSessionMapping version is 0
message AwsEmrStudioSessionMapping {
  string id = 1;

  string identity_id = 2 [json_name = "identity_id"];

  string identity_name = 3 [json_name = "identity_name"];

  string identity_type = 4 [json_name = "identity_type"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  string session_policy_arn = 6 [json_name = "session_policy_arn"];

  string studio_id = 7 [json_name = "studio_id"];

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;
}
