syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsMskCluster version is 0
message AwsMskCluster {
  string arn = 1;

  string bootstrap_brokers = 2 [json_name = "bootstrap_brokers"];

  string bootstrap_brokers_public_sasl_iam = 3 [json_name = "bootstrap_brokers_public_sasl_iam"];

  string bootstrap_brokers_public_sasl_scram = 4 [json_name = "bootstrap_brokers_public_sasl_scram"];

  string bootstrap_brokers_public_tls = 5 [json_name = "bootstrap_brokers_public_tls"];

  string bootstrap_brokers_sasl_iam = 6 [json_name = "bootstrap_brokers_sasl_iam"];

  string bootstrap_brokers_sasl_scram = 7 [json_name = "bootstrap_brokers_sasl_scram"];

  string bootstrap_brokers_tls = 8 [json_name = "bootstrap_brokers_tls"];

  string bootstrap_brokers_vpc_connectivity_sasl_iam = 9 [
    json_name = "bootstrap_brokers_vpc_connectivity_sasl_iam"
  ];

  string bootstrap_brokers_vpc_connectivity_sasl_scram = 10 [
    json_name = "bootstrap_brokers_vpc_connectivity_sasl_scram"
  ];

  string bootstrap_brokers_vpc_connectivity_tls = 11 [
    json_name = "bootstrap_brokers_vpc_connectivity_tls"
  ];

  string cluster_name = 12 [json_name = "cluster_name"];

  string cluster_uuid = 13 [json_name = "cluster_uuid"];

  string current_version = 14 [json_name = "current_version"];

  string enhanced_monitoring = 15 [json_name = "enhanced_monitoring"];

  string id = 16;

  string kafka_version = 17 [json_name = "kafka_version"];

  int64 number_of_broker_nodes = 18 [json_name = "number_of_broker_nodes"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 19;

  string storage_mode = 20 [json_name = "storage_mode"];

  map<string, string> tags = 21;

  map<string, string> tags_all = 22 [json_name = "tags_all"];

  string zookeeper_connect_string = 23 [json_name = "zookeeper_connect_string"];

  string zookeeper_connect_string_tls = 24 [json_name = "zookeeper_connect_string_tls"];

  BrokerNodeGroupInfo broker_node_group_info = 25 [json_name = "broker_node_group_info"];

  ClientAuthentication client_authentication = 26 [json_name = "client_authentication"];

  ConfigurationInfo configuration_info = 27 [json_name = "configuration_info"];

  EncryptionInfo encryption_info = 28 [json_name = "encryption_info"];

  LoggingInfo logging_info = 29 [json_name = "logging_info"];

  OpenMonitoring open_monitoring = 30 [json_name = "open_monitoring"];

  Rebalancing rebalancing = 31;

  repeated Timeouts timeouts = 32;

  google.protobuf.Value for_each = 33 [json_name = "for_each"];

  repeated string depends_on = 34 [json_name = "depends_on"];

  int32 count = 35;

  string provider = 36;

  terraform.v1.Lifecycle lifecycle = 37;

  message BrokerNodeGroupInfo {
    string az_distribution = 1 [json_name = "az_distribution"];

    repeated string client_subnets = 2 [json_name = "client_subnets"];

    string instance_type = 3 [json_name = "instance_type"];

    repeated string security_groups = 4 [json_name = "security_groups"];

    ConnectivityInfo connectivity_info = 5 [json_name = "connectivity_info"];

    StorageInfo storage_info = 6 [json_name = "storage_info"];

    message ConnectivityInfo {
      string network_type = 1 [json_name = "network_type"];

      PublicAccess public_access = 2 [json_name = "public_access"];

      VpcConnectivity vpc_connectivity = 3 [json_name = "vpc_connectivity"];

      message PublicAccess {
        string type = 1;
      }

      message VpcConnectivity {
        ClientAuthentication client_authentication = 1 [json_name = "client_authentication"];

        message ClientAuthentication {
          bool tls = 1;

          Sasl sasl = 2;

          message Sasl {
            bool iam = 1;

            bool scram = 2;
          }
        }
      }
    }

    message StorageInfo {
      EbsStorageInfo ebs_storage_info = 1 [json_name = "ebs_storage_info"];

      message EbsStorageInfo {
        int64 volume_size = 1 [json_name = "volume_size"];

        ProvisionedThroughput provisioned_throughput = 2 [json_name = "provisioned_throughput"];

        message ProvisionedThroughput {
          bool enabled = 1;

          int64 volume_throughput = 2 [json_name = "volume_throughput"];
        }
      }
    }
  }

  message ClientAuthentication {
    bool unauthenticated = 1;

    Sasl sasl = 2;

    Tls tls = 3;

    message Sasl {
      bool iam = 1;

      bool scram = 2;
    }

    message Tls {
      repeated string certificate_authority_arns = 1 [json_name = "certificate_authority_arns"];
    }
  }

  message ConfigurationInfo {
    string arn = 1;

    int64 revision = 2;
  }

  message EncryptionInfo {
    string encryption_at_rest_kms_key_arn = 1 [json_name = "encryption_at_rest_kms_key_arn"];

    EncryptionInTransit encryption_in_transit = 2 [json_name = "encryption_in_transit"];

    message EncryptionInTransit {
      string client_broker = 1 [json_name = "client_broker"];

      bool in_cluster = 2 [json_name = "in_cluster"];
    }
  }

  message LoggingInfo {
    BrokerLogs broker_logs = 1 [json_name = "broker_logs"];

    message BrokerLogs {
      CloudwatchLogs cloudwatch_logs = 1 [json_name = "cloudwatch_logs"];

      Firehose firehose = 2;

      S3 s3 = 3;

      message CloudwatchLogs {
        bool enabled = 1;

        string log_group = 2 [json_name = "log_group"];
      }

      message Firehose {
        string delivery_stream = 1 [json_name = "delivery_stream"];

        bool enabled = 2;
      }

      message S3 {
        string bucket = 1;

        bool enabled = 2;

        string prefix = 3;
      }
    }
  }

  message OpenMonitoring {
    Prometheus prometheus = 1;

    message Prometheus {
      JmxExporter jmx_exporter = 1 [json_name = "jmx_exporter"];

      NodeExporter node_exporter = 2 [json_name = "node_exporter"];

      message JmxExporter {
        bool enabled_in_broker = 1 [json_name = "enabled_in_broker"];
      }

      message NodeExporter {
        bool enabled_in_broker = 1 [json_name = "enabled_in_broker"];
      }
    }
  }

  message Rebalancing {
    string status = 1;
  }

  message Timeouts {
    string create = 1;

    string delete = 2;

    string update = 3;
  }
}

// AwsMskClusterPolicy version is 0
message AwsMskClusterPolicy {
  string cluster_arn = 1 [json_name = "cluster_arn"];

  string current_version = 2 [json_name = "current_version"];

  string id = 3;

  string policy = 4;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;
}

// AwsMskConfiguration version is 0
message AwsMskConfiguration {
  string arn = 1;

  string description = 2;

  string id = 3;

  repeated string kafka_versions = 4 [json_name = "kafka_versions"];

  int64 latest_revision = 5 [json_name = "latest_revision"];

  string name = 6;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 7;

  string server_properties = 8 [json_name = "server_properties"];

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// AwsMskReplicator version is 0
message AwsMskReplicator {
  string arn = 1;

  string current_version = 2 [json_name = "current_version"];

  string description = 3;

  string id = 4;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  string replicator_name = 6 [json_name = "replicator_name"];

  string service_execution_role_arn = 7 [json_name = "service_execution_role_arn"];

  map<string, string> tags = 8;

  map<string, string> tags_all = 9 [json_name = "tags_all"];

  repeated KafkaCluster kafka_cluster = 10 [json_name = "kafka_cluster"];

  ReplicationInfoList replication_info_list = 11 [json_name = "replication_info_list"];

  repeated Timeouts timeouts = 12;

  google.protobuf.Value for_each = 13 [json_name = "for_each"];

  repeated string depends_on = 14 [json_name = "depends_on"];

  int32 count = 15;

  string provider = 16;

  terraform.v1.Lifecycle lifecycle = 17;

  message KafkaCluster {
    AmazonMskCluster amazon_msk_cluster = 1 [json_name = "amazon_msk_cluster"];

    VpcConfig vpc_config = 2 [json_name = "vpc_config"];

    message AmazonMskCluster {
      string msk_cluster_arn = 1 [json_name = "msk_cluster_arn"];
    }

    message VpcConfig {
      repeated string security_groups_ids = 1 [json_name = "security_groups_ids"];

      repeated string subnet_ids = 2 [json_name = "subnet_ids"];
    }
  }

  message ReplicationInfoList {
    string source_kafka_cluster_alias = 1 [json_name = "source_kafka_cluster_alias"];

    string source_kafka_cluster_arn = 2 [json_name = "source_kafka_cluster_arn"];

    string target_compression_type = 3 [json_name = "target_compression_type"];

    string target_kafka_cluster_alias = 4 [json_name = "target_kafka_cluster_alias"];

    string target_kafka_cluster_arn = 5 [json_name = "target_kafka_cluster_arn"];

    repeated ConsumerGroupReplication consumer_group_replication = 6 [json_name = "consumer_group_replication"];

    repeated TopicReplication topic_replication = 7 [json_name = "topic_replication"];

    message ConsumerGroupReplication {
      repeated string consumer_groups_to_exclude = 1 [json_name = "consumer_groups_to_exclude"];

      repeated string consumer_groups_to_replicate = 2 [json_name = "consumer_groups_to_replicate"];

      bool detect_and_copy_new_consumer_groups = 3 [json_name = "detect_and_copy_new_consumer_groups"];

      bool synchronise_consumer_group_offsets = 4 [json_name = "synchronise_consumer_group_offsets"];
    }

    message TopicReplication {
      bool copy_access_control_lists_for_topics = 1 [json_name = "copy_access_control_lists_for_topics"];

      bool copy_topic_configurations = 2 [json_name = "copy_topic_configurations"];

      bool detect_and_copy_new_topics = 3 [json_name = "detect_and_copy_new_topics"];

      repeated string topics_to_exclude = 4 [json_name = "topics_to_exclude"];

      repeated string topics_to_replicate = 5 [json_name = "topics_to_replicate"];

      StartingPosition starting_position = 6 [json_name = "starting_position"];

      TopicNameConfiguration topic_name_configuration = 7 [json_name = "topic_name_configuration"];

      message StartingPosition {
        string type = 1;
      }

      message TopicNameConfiguration {
        string type = 1;
      }
    }
  }

  message Timeouts {
    string create = 1;

    string delete = 2;

    string update = 3;
  }
}

// AwsMskScramSecretAssociation version is 0
message AwsMskScramSecretAssociation {
  string cluster_arn = 1 [json_name = "cluster_arn"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  repeated string secret_arn_list = 4 [json_name = "secret_arn_list"];

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsMskServerlessCluster version is 0
message AwsMskServerlessCluster {
  string arn = 1;

  string bootstrap_brokers_sasl_iam = 2 [json_name = "bootstrap_brokers_sasl_iam"];

  string cluster_name = 3 [json_name = "cluster_name"];

  string cluster_uuid = 4 [json_name = "cluster_uuid"];

  string id = 5;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  map<string, string> tags = 7;

  map<string, string> tags_all = 8 [json_name = "tags_all"];

  ClientAuthentication client_authentication = 9 [json_name = "client_authentication"];

  repeated Timeouts timeouts = 10;

  repeated VpcConfig vpc_config = 11 [json_name = "vpc_config"];

  google.protobuf.Value for_each = 12 [json_name = "for_each"];

  repeated string depends_on = 13 [json_name = "depends_on"];

  int32 count = 14;

  string provider = 15;

  terraform.v1.Lifecycle lifecycle = 16;

  message ClientAuthentication {
    Sasl sasl = 1;

    message Sasl {
      Iam iam = 1;

      message Iam {
        bool enabled = 1;
      }
    }
  }

  message Timeouts {
    string create = 1;

    string delete = 2;
  }

  message VpcConfig {
    repeated string security_group_ids = 1 [json_name = "security_group_ids"];

    repeated string subnet_ids = 2 [json_name = "subnet_ids"];
  }
}

// AwsMskSingleScramSecretAssociation version is 0
message AwsMskSingleScramSecretAssociation {
  string cluster_arn = 1 [json_name = "cluster_arn"];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  string secret_arn = 4 [json_name = "secret_arn"];

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsMskTopic version is 0
message AwsMskTopic {
  string arn = 1;

  string cluster_arn = 2 [json_name = "cluster_arn"];

  string configs = 3;

  string configs_actual = 4 [json_name = "configs_actual"];

  string name = 5;

  int64 partition_count = 6 [json_name = "partition_count"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 7;

  int64 replication_factor = 8 [json_name = "replication_factor"];

  repeated Timeouts timeouts = 9;

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string update = 3;
  }
}

// AwsMskVpcConnection version is 0
message AwsMskVpcConnection {
  string arn = 1;

  string authentication = 2;

  repeated string client_subnets = 3 [json_name = "client_subnets"];

  string id = 4;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  repeated string security_groups = 6 [json_name = "security_groups"];

  map<string, string> tags = 7;

  map<string, string> tags_all = 8 [json_name = "tags_all"];

  string target_cluster_arn = 9 [json_name = "target_cluster_arn"];

  string vpc_id = 10 [json_name = "vpc_id"];

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;
}
