syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsNetworkAcl version is 0
message AwsNetworkAcl {
  string arn = 1;

  repeated Egress egress = 2;

  string id = 3;

  repeated Ingress ingress = 4;

  string owner_id = 5 [json_name = "owner_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 6;

  repeated string subnet_ids = 7 [json_name = "subnet_ids"];

  map<string, string> tags = 8;

  map<string, string> tags_all = 9 [json_name = "tags_all"];

  string vpc_id = 10 [json_name = "vpc_id"];

  google.protobuf.Value for_each = 11 [json_name = "for_each"];

  repeated string depends_on = 12 [json_name = "depends_on"];

  int32 count = 13;

  string provider = 14;

  terraform.v1.Lifecycle lifecycle = 15;

  message Egress {
    // action: string
    string action = 1;

    // cidr_block: string
    string cidr_block = 2 [json_name = "cidr_block"];

    // from_port: number
    int64 from_port = 3 [json_name = "from_port"];

    // icmp_code: number
    int64 icmp_code = 4 [json_name = "icmp_code"];

    // icmp_type: number
    int64 icmp_type = 5 [json_name = "icmp_type"];

    // ipv6_cidr_block: string
    string ipv6_cidr_block = 6 [json_name = "ipv6_cidr_block"];

    // protocol: string
    string protocol = 7;

    // rule_no: number
    int64 rule_no = 8 [json_name = "rule_no"];

    // to_port: number
    int64 to_port = 9 [json_name = "to_port"];
  }

  message Ingress {
    // action: string
    string action = 1;

    // cidr_block: string
    string cidr_block = 2 [json_name = "cidr_block"];

    // from_port: number
    int64 from_port = 3 [json_name = "from_port"];

    // icmp_code: number
    int64 icmp_code = 4 [json_name = "icmp_code"];

    // icmp_type: number
    int64 icmp_type = 5 [json_name = "icmp_type"];

    // ipv6_cidr_block: string
    string ipv6_cidr_block = 6 [json_name = "ipv6_cidr_block"];

    // protocol: string
    string protocol = 7;

    // rule_no: number
    int64 rule_no = 8 [json_name = "rule_no"];

    // to_port: number
    int64 to_port = 9 [json_name = "to_port"];
  }
}

// AwsNetworkAclAssociation version is 0
message AwsNetworkAclAssociation {
  string id = 1;

  string network_acl_id = 2 [json_name = "network_acl_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  string subnet_id = 4 [json_name = "subnet_id"];

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsNetworkAclRule version is 0
message AwsNetworkAclRule {
  string cidr_block = 1 [json_name = "cidr_block"];

  bool egress = 2;

  int64 from_port = 3 [json_name = "from_port"];

  int64 icmp_code = 4 [json_name = "icmp_code"];

  int64 icmp_type = 5 [json_name = "icmp_type"];

  string id = 6;

  string ipv6_cidr_block = 7 [json_name = "ipv6_cidr_block"];

  string network_acl_id = 8 [json_name = "network_acl_id"];

  string protocol = 9;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 10;

  string rule_action = 11 [json_name = "rule_action"];

  int64 rule_number = 12 [json_name = "rule_number"];

  int64 to_port = 13 [json_name = "to_port"];

  google.protobuf.Value for_each = 14 [json_name = "for_each"];

  repeated string depends_on = 15 [json_name = "depends_on"];

  int32 count = 16;

  string provider = 17;

  terraform.v1.Lifecycle lifecycle = 18;
}

// AwsNetworkInterface version is 0
message AwsNetworkInterface {
  string arn = 1;

  string description = 2;

  bool enable_primary_ipv6 = 3 [json_name = "enable_primary_ipv6"];

  string id = 4;

  string interface_type = 5 [json_name = "interface_type"];

  int64 ipv4_prefix_count = 6 [json_name = "ipv4_prefix_count"];

  repeated string ipv4_prefixes = 7 [json_name = "ipv4_prefixes"];

  int64 ipv6_address_count = 8 [json_name = "ipv6_address_count"];

  repeated string ipv6_address_list = 9 [json_name = "ipv6_address_list"];

  bool ipv6_address_list_enabled = 10 [json_name = "ipv6_address_list_enabled"];

  repeated string ipv6_addresses = 11 [json_name = "ipv6_addresses"];

  int64 ipv6_prefix_count = 12 [json_name = "ipv6_prefix_count"];

  repeated string ipv6_prefixes = 13 [json_name = "ipv6_prefixes"];

  string mac_address = 14 [json_name = "mac_address"];

  string outpost_arn = 15 [json_name = "outpost_arn"];

  string owner_id = 16 [json_name = "owner_id"];

  string private_dns_name = 17 [json_name = "private_dns_name"];

  string private_ip = 18 [json_name = "private_ip"];

  repeated string private_ip_list = 19 [json_name = "private_ip_list"];

  bool private_ip_list_enabled = 20 [json_name = "private_ip_list_enabled"];

  repeated string private_ips = 21 [json_name = "private_ips"];

  int64 private_ips_count = 22 [json_name = "private_ips_count"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 23;

  repeated string security_groups = 24 [json_name = "security_groups"];

  bool source_dest_check = 25 [json_name = "source_dest_check"];

  string subnet_id = 26 [json_name = "subnet_id"];

  map<string, string> tags = 27;

  map<string, string> tags_all = 28 [json_name = "tags_all"];

  repeated Attachment attachment = 29;

  EnaSrdSpecification ena_srd_specification = 30 [json_name = "ena_srd_specification"];

  google.protobuf.Value for_each = 31 [json_name = "for_each"];

  repeated string depends_on = 32 [json_name = "depends_on"];

  int32 count = 33;

  string provider = 34;

  terraform.v1.Lifecycle lifecycle = 35;

  message Attachment {
    string attachment_id = 1 [json_name = "attachment_id"];

    int64 device_index = 2 [json_name = "device_index"];

    string instance = 3;

    int64 network_card_index = 4 [json_name = "network_card_index"];
  }

  message EnaSrdSpecification {
    bool ena_srd_enabled = 1 [json_name = "ena_srd_enabled"];

    EnaSrdUdpSpecification ena_srd_udp_specification = 2 [json_name = "ena_srd_udp_specification"];

    message EnaSrdUdpSpecification {
      bool ena_srd_udp_enabled = 1 [json_name = "ena_srd_udp_enabled"];
    }
  }
}

// AwsNetworkInterfaceAttachment version is 0
message AwsNetworkInterfaceAttachment {
  string attachment_id = 1 [json_name = "attachment_id"];

  int64 device_index = 2 [json_name = "device_index"];

  string id = 3;

  string instance_id = 4 [json_name = "instance_id"];

  int64 network_card_index = 5 [json_name = "network_card_index"];

  string network_interface_id = 6 [json_name = "network_interface_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 7;

  string status = 8;

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;
}

// AwsNetworkInterfacePermission version is 0
message AwsNetworkInterfacePermission {
  string aws_account_id = 1 [json_name = "aws_account_id"];

  string network_interface_id = 2 [json_name = "network_interface_id"];

  string network_interface_permission_id = 3 [json_name = "network_interface_permission_id"];

  string permission = 4;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 5;

  repeated Timeouts timeouts = 6;

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;
  }
}

// AwsNetworkInterfaceSgAttachment version is 0
message AwsNetworkInterfaceSgAttachment {
  string id = 1;

  string network_interface_id = 2 [json_name = "network_interface_id"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  string security_group_id = 4 [json_name = "security_group_id"];

  repeated Timeouts timeouts = 5;

  google.protobuf.Value for_each = 6 [json_name = "for_each"];

  repeated string depends_on = 7 [json_name = "depends_on"];

  int32 count = 8;

  string provider = 9;

  terraform.v1.Lifecycle lifecycle = 10;

  message Timeouts {
    string create = 1;

    string delete = 2;

    string read = 3;
  }
}
