syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsObservabilityadminCentralizationRuleForOrganization version is 0
message AwsObservabilityadminCentralizationRuleForOrganization {
  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 1;

  string rule_arn = 2 [json_name = "rule_arn"];

  string rule_name = 3 [json_name = "rule_name"];

  map<string, string> tags = 4;

  map<string, string> tags_all = 5 [json_name = "tags_all"];

  repeated Rule rule = 6;

  repeated Timeouts timeouts = 7;

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;

  message Rule {
    repeated Destination destination = 1;

    repeated Source source = 2;

    message Destination {
      string account = 1;

      string region = 2;

      repeated DestinationLogsConfiguration destination_logs_configuration = 3 [json_name = "destination_logs_configuration"];

      message DestinationLogsConfiguration {
        repeated BackupConfiguration backup_configuration = 1 [json_name = "backup_configuration"];

        repeated LogGroupNameConfiguration log_group_name_configuration = 2 [json_name = "log_group_name_configuration"];

        repeated LogsEncryptionConfiguration logs_encryption_configuration = 3 [json_name = "logs_encryption_configuration"];

        message BackupConfiguration {
          string kms_key_arn = 1 [json_name = "kms_key_arn"];

          string region = 2;
        }

        message LogGroupNameConfiguration {
          string log_group_name_pattern = 1 [json_name = "log_group_name_pattern"];
        }

        message LogsEncryptionConfiguration {
          string encryption_conflict_resolution_strategy = 1 [
            json_name = "encryption_conflict_resolution_strategy"
          ];

          string encryption_strategy = 2 [json_name = "encryption_strategy"];

          string kms_key_arn = 3 [json_name = "kms_key_arn"];
        }
      }
    }

    message Source {
      repeated string regions = 1;

      string scope = 2;

      repeated SourceLogsConfiguration source_logs_configuration = 3 [json_name = "source_logs_configuration"];

      message SourceLogsConfiguration {
        string data_source_selection_criteria = 1 [json_name = "data_source_selection_criteria"];

        string encrypted_log_group_strategy = 2 [json_name = "encrypted_log_group_strategy"];

        string log_group_selection_criteria = 3 [json_name = "log_group_selection_criteria"];
      }
    }
  }

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string update = 2;
  }
}

// AwsObservabilityadminTelemetryEnrichment version is 0
message AwsObservabilityadminTelemetryEnrichment {
  string aws_resource_explorer_managed_view_arn = 1 [
    json_name = "aws_resource_explorer_managed_view_arn"
  ];

  string id = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  repeated Timeouts timeouts = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;
  }
}

// AwsObservabilityadminTelemetryPipeline version is 0
message AwsObservabilityadminTelemetryPipeline {
  string arn = 1;

  string name = 2;

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 3;

  map<string, string> tags = 4;

  map<string, string> tags_all = 5 [json_name = "tags_all"];

  repeated Configuration configuration = 6;

  repeated Timeouts timeouts = 7;

  google.protobuf.Value for_each = 8 [json_name = "for_each"];

  repeated string depends_on = 9 [json_name = "depends_on"];

  int32 count = 10;

  string provider = 11;

  terraform.v1.Lifecycle lifecycle = 12;

  message Configuration {
    string body = 1;
  }

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string update = 3;
  }
}
