syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsQbusinessApplication version is 0
message AwsQbusinessApplication {
  string arn = 1;

  // A description of the Amazon Q application.
  string description = 2;

  // The display name of the Amazon Q application.
  string display_name = 3 [json_name = "display_name"];

  // The Amazon Resource Name (ARN) of the IAM service role that provides permissions
  // for the Amazon Q application.
  string iam_service_role_arn = 4 [json_name = "iam_service_role_arn"];

  string id = 5;

  string identity_center_application_arn = 6 [json_name = "identity_center_application_arn"];

  // ARN of the IAM Identity Center instance you are either creating for—or connecting
  // to—your Amazon Q Business application
  string identity_center_instance_arn = 7 [json_name = "identity_center_instance_arn"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 8;

  map<string, string> tags = 9;

  map<string, string> tags_all = 10 [json_name = "tags_all"];

  repeated AttachmentsConfiguration attachments_configuration = 11 [json_name = "attachments_configuration"];

  repeated EncryptionConfiguration encryption_configuration = 12 [json_name = "encryption_configuration"];

  repeated Timeouts timeouts = 13;

  google.protobuf.Value for_each = 14 [json_name = "for_each"];

  repeated string depends_on = 15 [json_name = "depends_on"];

  int32 count = 16;

  string provider = 17;

  terraform.v1.Lifecycle lifecycle = 18;

  message AttachmentsConfiguration {
    // Status information about whether file upload functionality is activated or
    // deactivated for your end user.
    string attachments_control_mode = 1 [json_name = "attachments_control_mode"];
  }

  message EncryptionConfiguration {
    // The identifier of the AWS KMS key that is used to encrypt your data. Amazon Q
    // doesn't support asymmetric keys.
    string kms_key_id = 1 [json_name = "kms_key_id"];
  }

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string update = 3;
  }
}
