syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsRolesanywhereProfile version is 0
message AwsRolesanywhereProfile {
  bool accept_role_session_name = 1 [json_name = "accept_role_session_name"];

  string arn = 2;

  int64 duration_seconds = 3 [json_name = "duration_seconds"];

  bool enabled = 4;

  string id = 5;

  repeated string managed_policy_arns = 6 [json_name = "managed_policy_arns"];

  string name = 7;

  bool require_instance_properties = 8 [json_name = "require_instance_properties"];

  repeated string role_arns = 9 [json_name = "role_arns"];

  string session_policy = 10 [json_name = "session_policy"];

  map<string, string> tags = 11;

  map<string, string> tags_all = 12 [json_name = "tags_all"];

  google.protobuf.Value for_each = 13 [json_name = "for_each"];

  repeated string depends_on = 14 [json_name = "depends_on"];

  int32 count = 15;

  string provider = 16;

  terraform.v1.Lifecycle lifecycle = 17;
}

// AwsRolesanywhereTrustAnchor version is 0
message AwsRolesanywhereTrustAnchor {
  string arn = 1;

  bool enabled = 2;

  string id = 3;

  string name = 4;

  map<string, string> tags = 5;

  map<string, string> tags_all = 6 [json_name = "tags_all"];

  repeated NotificationSettings notification_settings = 7 [json_name = "notification_settings"];

  Source source = 8;

  google.protobuf.Value for_each = 9 [json_name = "for_each"];

  repeated string depends_on = 10 [json_name = "depends_on"];

  int32 count = 11;

  string provider = 12;

  terraform.v1.Lifecycle lifecycle = 13;

  message NotificationSettings {
    string channel = 1;

    string configured_by = 2 [json_name = "configured_by"];

    bool enabled = 3;

    string event = 4;

    int64 threshold = 5;
  }

  message Source {
    string source_type = 1 [json_name = "source_type"];

    SourceData source_data = 2 [json_name = "source_data"];

    message SourceData {
      string acm_pca_arn = 1 [json_name = "acm_pca_arn"];

      string x509_certificate_data = 2 [json_name = "x509_certificate_data"];
    }
  }
}
