syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsShieldApplicationLayerAutomaticResponse version is 0
message AwsShieldApplicationLayerAutomaticResponse {
  string action = 1;

  string id = 2;

  string resource_arn = 3 [json_name = "resource_arn"];

  repeated Timeouts timeouts = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string update = 3;
  }
}

// AwsShieldDrtAccessLogBucketAssociation version is 0
message AwsShieldDrtAccessLogBucketAssociation {
  string id = 1;

  string log_bucket = 2 [json_name = "log_bucket"];

  // Unused
  string role_arn_association_id = 3 [json_name = "role_arn_association_id"];

  repeated Timeouts timeouts = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;
  }
}

// AwsShieldDrtAccessRoleArnAssociation version is 0
message AwsShieldDrtAccessRoleArnAssociation {
  string id = 1;

  string role_arn = 2 [json_name = "role_arn"];

  repeated Timeouts timeouts = 3;

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;

  message Timeouts {
    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string create = 1;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours). Setting a timeout for a Delete operation is only
    // applicable if changes are saved into state before the destroy operation occurs.
    string delete = 2;

    // A string that can be [parsed as a
    // duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit
    // suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m"
    // (minutes), "h" (hours).
    string update = 3;
  }
}

// AwsShieldProactiveEngagement version is 0
message AwsShieldProactiveEngagement {
  bool enabled = 1;

  string id = 2;

  repeated EmergencyContact emergency_contact = 3 [json_name = "emergency_contact"];

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;

  message EmergencyContact {
    string contact_notes = 1 [json_name = "contact_notes"];

    string email_address = 2 [json_name = "email_address"];

    string phone_number = 3 [json_name = "phone_number"];
  }
}

// AwsShieldProtection version is 0
message AwsShieldProtection {
  string arn = 1;

  string id = 2;

  string name = 3;

  string resource_arn = 4 [json_name = "resource_arn"];

  map<string, string> tags = 5;

  map<string, string> tags_all = 6 [json_name = "tags_all"];

  google.protobuf.Value for_each = 7 [json_name = "for_each"];

  repeated string depends_on = 8 [json_name = "depends_on"];

  int32 count = 9;

  string provider = 10;

  terraform.v1.Lifecycle lifecycle = 11;
}

// AwsShieldProtectionGroup version is 0
message AwsShieldProtectionGroup {
  string aggregation = 1;

  string id = 2;

  repeated string members = 3;

  string pattern = 4;

  string protection_group_arn = 5 [json_name = "protection_group_arn"];

  string protection_group_id = 6 [json_name = "protection_group_id"];

  string resource_type = 7 [json_name = "resource_type"];

  map<string, string> tags = 8;

  map<string, string> tags_all = 9 [json_name = "tags_all"];

  google.protobuf.Value for_each = 10 [json_name = "for_each"];

  repeated string depends_on = 11 [json_name = "depends_on"];

  int32 count = 12;

  string provider = 13;

  terraform.v1.Lifecycle lifecycle = 14;
}

// AwsShieldProtectionHealthCheckAssociation version is 0
message AwsShieldProtectionHealthCheckAssociation {
  string health_check_arn = 1 [json_name = "health_check_arn"];

  string id = 2;

  string shield_protection_id = 3 [json_name = "shield_protection_id"];

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}

// AwsShieldSubscription version is 0
message AwsShieldSubscription {
  // Whether to automatically renew the subscription when it expires.
  string auto_renew = 1 [json_name = "auto_renew"];

  string id = 2;

  bool skip_destroy = 3 [json_name = "skip_destroy"];

  google.protobuf.Value for_each = 4 [json_name = "for_each"];

  repeated string depends_on = 5 [json_name = "depends_on"];

  int32 count = 6;

  string provider = 7;

  terraform.v1.Lifecycle lifecycle = 8;
}
