syntax = "proto3";

// Provider: aws 6
package terraform.aws.resources.v6;

import "google/protobuf/struct.proto";

import "terraform/v1/meta.proto";

// AwsSqsQueue version is 0
message AwsSqsQueue {
  string arn = 1;

  bool content_based_deduplication = 2 [json_name = "content_based_deduplication"];

  string deduplication_scope = 3 [json_name = "deduplication_scope"];

  int64 delay_seconds = 4 [json_name = "delay_seconds"];

  bool fifo_queue = 5 [json_name = "fifo_queue"];

  string fifo_throughput_limit = 6 [json_name = "fifo_throughput_limit"];

  string id = 7;

  int64 kms_data_key_reuse_period_seconds = 8 [json_name = "kms_data_key_reuse_period_seconds"];

  string kms_master_key_id = 9 [json_name = "kms_master_key_id"];

  int64 max_message_size = 10 [json_name = "max_message_size"];

  int64 message_retention_seconds = 11 [json_name = "message_retention_seconds"];

  string name = 12;

  string name_prefix = 13 [json_name = "name_prefix"];

  string policy = 14;

  int64 receive_wait_time_seconds = 15 [json_name = "receive_wait_time_seconds"];

  string redrive_allow_policy = 16 [json_name = "redrive_allow_policy"];

  string redrive_policy = 17 [json_name = "redrive_policy"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 18;

  bool sqs_managed_sse_enabled = 19 [json_name = "sqs_managed_sse_enabled"];

  map<string, string> tags = 20;

  map<string, string> tags_all = 21 [json_name = "tags_all"];

  string url = 22;

  int64 visibility_timeout_seconds = 23 [json_name = "visibility_timeout_seconds"];

  repeated Timeouts timeouts = 24;

  google.protobuf.Value for_each = 25 [json_name = "for_each"];

  repeated string depends_on = 26 [json_name = "depends_on"];

  int32 count = 27;

  string provider = 28;

  terraform.v1.Lifecycle lifecycle = 29;

  message Timeouts {
    string create = 1;

    string delete = 2;

    string update = 3;
  }
}

// AwsSqsQueuePolicy version is 1
message AwsSqsQueuePolicy {
  string id = 1;

  string policy = 2;

  string queue_url = 3 [json_name = "queue_url"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsSqsQueueRedriveAllowPolicy version is 0
message AwsSqsQueueRedriveAllowPolicy {
  string id = 1;

  string queue_url = 2 [json_name = "queue_url"];

  string redrive_allow_policy = 3 [json_name = "redrive_allow_policy"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}

// AwsSqsQueueRedrivePolicy version is 0
message AwsSqsQueueRedrivePolicy {
  string id = 1;

  string queue_url = 2 [json_name = "queue_url"];

  string redrive_policy = 3 [json_name = "redrive_policy"];

  // Region where this resource will be
  // ed](https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints).
  // Defaults to the Region set in the [provider
  // ry.terraform.io/providers/hashicorp/aws/latest/docs#aws-configuration-reference).
  string region = 4;

  google.protobuf.Value for_each = 5 [json_name = "for_each"];

  repeated string depends_on = 6 [json_name = "depends_on"];

  int32 count = 7;

  string provider = 8;

  terraform.v1.Lifecycle lifecycle = 9;
}
